# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(552, 875)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        mainwindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.robotControl = QtWidgets.QGroupBox(self.centralwidget)
        self.robotControl.setEnabled(True)
        self.robotControl.setGeometry(QtCore.QRect(20, 50, 511, 381))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.robotControl.sizePolicy().hasHeightForWidth())
        self.robotControl.setSizePolicy(sizePolicy)
        self.robotControl.setObjectName("robotControl")
        self.initializeProgressLabel = QtWidgets.QLabel(self.robotControl)
        self.initializeProgressLabel.setEnabled(False)
        self.initializeProgressLabel.setGeometry(QtCore.QRect(9, 70, 141, 17))
        self.initializeProgressLabel.setObjectName("initializeProgressLabel")
        self.initializeProgressBar = QtWidgets.QProgressBar(self.robotControl)
        self.initializeProgressBar.setEnabled(False)
        self.initializeProgressBar.setGeometry(QtCore.QRect(9, 90, 118, 23))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(False)
        font.setWeight(50)
        self.initializeProgressBar.setFont(font)
        self.initializeProgressBar.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.initializeProgressBar.setProperty("value", 0)
        self.initializeProgressBar.setObjectName("initializeProgressBar")
        self.Settings = QtWidgets.QGroupBox(self.robotControl)
        self.Settings.setEnabled(True)
        self.Settings.setGeometry(QtCore.QRect(160, 20, 201, 135))
        self.Settings.setAutoFillBackground(False)
        self.Settings.setFlat(False)
        self.Settings.setCheckable(True)
        self.Settings.setChecked(True)
        self.Settings.setObjectName("Settings")
        self.layoutWidget = QtWidgets.QWidget(self.Settings)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 43, 181, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.speedLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.speedLayout.setContentsMargins(0, 0, 0, 0)
        self.speedLayout.setObjectName("speedLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sliderSpeedLabel = QtWidgets.QLabel(self.layoutWidget)
        self.sliderSpeedLabel.setObjectName("sliderSpeedLabel")
        self.verticalLayout_2.addWidget(self.sliderSpeedLabel)
        self.panSpeedLabel = QtWidgets.QLabel(self.layoutWidget)
        self.panSpeedLabel.setObjectName("panSpeedLabel")
        self.verticalLayout_2.addWidget(self.panSpeedLabel)
        self.tiltSpeedLabel = QtWidgets.QLabel(self.layoutWidget)
        self.tiltSpeedLabel.setObjectName("tiltSpeedLabel")
        self.verticalLayout_2.addWidget(self.tiltSpeedLabel)
        self.speedLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sliderSpeedSpin = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.sliderSpeedSpin.setDecimals(1)
        self.sliderSpeedSpin.setProperty("value", 20.0)
        self.sliderSpeedSpin.setObjectName("sliderSpeedSpin")
        self.verticalLayout_3.addWidget(self.sliderSpeedSpin)
        self.panSpeedSpin = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.panSpeedSpin.setDecimals(1)
        self.panSpeedSpin.setProperty("value", 5.0)
        self.panSpeedSpin.setObjectName("panSpeedSpin")
        self.verticalLayout_3.addWidget(self.panSpeedSpin)
        self.tiltSpeedSpin = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.tiltSpeedSpin.setDecimals(1)
        self.tiltSpeedSpin.setProperty("value", 5.0)
        self.tiltSpeedSpin.setObjectName("tiltSpeedSpin")
        self.verticalLayout_3.addWidget(self.tiltSpeedSpin)
        self.speedLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radpersec = QtWidgets.QLabel(self.layoutWidget)
        self.radpersec.setMinimumSize(QtCore.QSize(40, 0))
        self.radpersec.setObjectName("radpersec")
        self.verticalLayout_4.addWidget(self.radpersec)
        self.radpersec_2 = QtWidgets.QLabel(self.layoutWidget)
        self.radpersec_2.setMinimumSize(QtCore.QSize(40, 0))
        self.radpersec_2.setObjectName("radpersec_2")
        self.verticalLayout_4.addWidget(self.radpersec_2)
        self.radpersec_3 = QtWidgets.QLabel(self.layoutWidget)
        self.radpersec_3.setMinimumSize(QtCore.QSize(40, 0))
        self.radpersec_3.setObjectName("radpersec_3")
        self.verticalLayout_4.addWidget(self.radpersec_3)
        self.speedLayout.addLayout(self.verticalLayout_4)
        self.setSpeedLabel = QtWidgets.QLabel(self.Settings)
        self.setSpeedLabel.setGeometry(QtCore.QRect(10, 25, 100, 16))
        self.setSpeedLabel.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.setSpeedLabel.setFont(font)
        self.setSpeedLabel.setObjectName("setSpeedLabel")
        self.detailedSettingsButton = QtWidgets.QToolButton(self.Settings)
        self.detailedSettingsButton.setGeometry(QtCore.QRect(80, 0, 26, 24))
        self.detailedSettingsButton.setObjectName("detailedSettingsButton")
        self.layoutWidget1 = QtWidgets.QWidget(self.robotControl)
        self.layoutWidget1.setGeometry(QtCore.QRect(370, 50, 131, 101))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.currentPoslabel = QtWidgets.QLabel(self.layoutWidget1)
        self.currentPoslabel.setAlignment(QtCore.Qt.AlignCenter)
        self.currentPoslabel.setObjectName("currentPoslabel")
        self.gridLayout.addWidget(self.currentPoslabel, 0, 1, 1, 1)
        self.currentSliderLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.currentSliderLabel.setObjectName("currentSliderLabel")
        self.gridLayout.addWidget(self.currentSliderLabel, 1, 0, 1, 1)
        self.sliderCurrentPos = QtWidgets.QLabel(self.layoutWidget1)
        self.sliderCurrentPos.setAlignment(QtCore.Qt.AlignCenter)
        self.sliderCurrentPos.setObjectName("sliderCurrentPos")
        self.gridLayout.addWidget(self.sliderCurrentPos, 1, 1, 1, 1)
        self.currentPanLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.currentPanLabel.setObjectName("currentPanLabel")
        self.gridLayout.addWidget(self.currentPanLabel, 2, 0, 1, 1)
        self.panCurrentPos = QtWidgets.QLabel(self.layoutWidget1)
        self.panCurrentPos.setAlignment(QtCore.Qt.AlignCenter)
        self.panCurrentPos.setObjectName("panCurrentPos")
        self.gridLayout.addWidget(self.panCurrentPos, 2, 1, 1, 1)
        self.currentTiltLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.currentTiltLabel.setObjectName("currentTiltLabel")
        self.gridLayout.addWidget(self.currentTiltLabel, 3, 0, 1, 1)
        self.tiltCurrentPos = QtWidgets.QLabel(self.layoutWidget1)
        self.tiltCurrentPos.setAlignment(QtCore.Qt.AlignCenter)
        self.tiltCurrentPos.setObjectName("tiltCurrentPos")
        self.gridLayout.addWidget(self.tiltCurrentPos, 3, 1, 1, 1)
        self.manualOperation = QtWidgets.QGroupBox(self.robotControl)
        self.manualOperation.setGeometry(QtCore.QRect(10, 140, 491, 231))
        self.manualOperation.setCheckable(False)
        self.manualOperation.setObjectName("manualOperation")
        self.layoutWidget2 = QtWidgets.QWidget(self.manualOperation)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 141, 89))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sliderOriginButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.sliderOriginButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.sliderOriginButton.setAutoDefault(True)
        self.sliderOriginButton.setObjectName("sliderOriginButton")
        self.verticalLayout.addWidget(self.sliderOriginButton)
        self.freeButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.freeButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.freeButton.setAutoDefault(True)
        self.freeButton.setObjectName("freeButton")
        self.verticalLayout.addWidget(self.freeButton)
        self.rebootButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.rebootButton.setMinimumSize(QtCore.QSize(50, 0))
        self.rebootButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.rebootButton.setAutoDefault(True)
        self.rebootButton.setDefault(False)
        self.rebootButton.setFlat(False)
        self.rebootButton.setObjectName("rebootButton")
        self.verticalLayout.addWidget(self.rebootButton)
        self.layoutWidget3 = QtWidgets.QWidget(self.manualOperation)
        self.layoutWidget3.setGeometry(QtCore.QRect(184, 30, 303, 92))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.positionControlLayout = QtWidgets.QGridLayout(self.layoutWidget3)
        self.positionControlLayout.setContentsMargins(0, 0, 0, 0)
        self.positionControlLayout.setObjectName("positionControlLayout")
        self.panLabel = QtWidgets.QLabel(self.layoutWidget3)
        self.panLabel.setObjectName("panLabel")
        self.positionControlLayout.addWidget(self.panLabel, 1, 0, 1, 1)
        self.tiltMoveExe = QtWidgets.QPushButton(self.layoutWidget3)
        self.tiltMoveExe.setMaximumSize(QtCore.QSize(24, 16777215))
        self.tiltMoveExe.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/GUI_icons/exec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tiltMoveExe.setIcon(icon)
        self.tiltMoveExe.setAutoDefault(True)
        self.tiltMoveExe.setObjectName("tiltMoveExe")
        self.positionControlLayout.addWidget(self.tiltMoveExe, 2, 2, 1, 1)
        self.tiltPosSpin = MyDoubleSpinBox(self.layoutWidget3)
        self.tiltPosSpin.setDecimals(2)
        self.tiltPosSpin.setMinimum(-360.0)
        self.tiltPosSpin.setMaximum(360.0)
        self.tiltPosSpin.setSingleStep(0.1)
        self.tiltPosSpin.setObjectName("tiltPosSpin")
        self.positionControlLayout.addWidget(self.tiltPosSpin, 2, 1, 1, 1)
        self.sliderLabel = QtWidgets.QLabel(self.layoutWidget3)
        self.sliderLabel.setObjectName("sliderLabel")
        self.positionControlLayout.addWidget(self.sliderLabel, 0, 0, 1, 1)
        self.panMoveExe = QtWidgets.QPushButton(self.layoutWidget3)
        self.panMoveExe.setMaximumSize(QtCore.QSize(24, 16777215))
        self.panMoveExe.setText("")
        self.panMoveExe.setIcon(icon)
        self.panMoveExe.setAutoDefault(True)
        self.panMoveExe.setObjectName("panMoveExe")
        self.positionControlLayout.addWidget(self.panMoveExe, 1, 2, 1, 1)
        self.sliderMoveExe = QtWidgets.QPushButton(self.layoutWidget3)
        self.sliderMoveExe.setMaximumSize(QtCore.QSize(24, 16777215))
        self.sliderMoveExe.setText("")
        self.sliderMoveExe.setIcon(icon)
        self.sliderMoveExe.setAutoDefault(True)
        self.sliderMoveExe.setObjectName("sliderMoveExe")
        self.positionControlLayout.addWidget(self.sliderMoveExe, 0, 2, 1, 1)
        self.panPosSpin = MyDoubleSpinBox(self.layoutWidget3)
        self.panPosSpin.setDecimals(2)
        self.panPosSpin.setMinimum(-360.0)
        self.panPosSpin.setMaximum(360.0)
        self.panPosSpin.setSingleStep(0.1)
        self.panPosSpin.setObjectName("panPosSpin")
        self.positionControlLayout.addWidget(self.panPosSpin, 1, 1, 1, 1)
        self.tiltLabel = QtWidgets.QLabel(self.layoutWidget3)
        self.tiltLabel.setObjectName("tiltLabel")
        self.positionControlLayout.addWidget(self.tiltLabel, 2, 0, 1, 1)
        self.sliderPosSpin = MyDoubleSpinBox(self.layoutWidget3)
        self.sliderPosSpin.setDecimals(2)
        self.sliderPosSpin.setMinimum(-4000.0)
        self.sliderPosSpin.setMaximum(4000.0)
        self.sliderPosSpin.setSingleStep(5.0)
        self.sliderPosSpin.setObjectName("sliderPosSpin")
        self.positionControlLayout.addWidget(self.sliderPosSpin, 0, 1, 1, 1)
        self.originLabel = QtWidgets.QLabel(self.manualOperation)
        self.originLabel.setGeometry(QtCore.QRect(350, 195, 51, 20))
        self.originLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.originLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(False)
        font.setWeight(50)
        self.originLabel.setFont(font)
        self.originLabel.setObjectName("originLabel")
        self.layoutWidget4 = QtWidgets.QWidget(self.manualOperation)
        self.layoutWidget4.setGeometry(QtCore.QRect(404, 190, 71, 32))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.originLayout = QtWidgets.QGridLayout(self.layoutWidget4)
        self.originLayout.setContentsMargins(0, 0, 0, 0)
        self.originLayout.setObjectName("originLayout")
        self.goHomeButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.goHomeButton.setMinimumSize(QtCore.QSize(30, 30))
        self.goHomeButton.setMaximumSize(QtCore.QSize(30, 30))
        self.goHomeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/GUI_icons/goTo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.goHomeButton.setIcon(icon1)
        self.goHomeButton.setIconSize(QtCore.QSize(30, 30))
        self.goHomeButton.setObjectName("goHomeButton")
        self.originLayout.addWidget(self.goHomeButton, 0, 1, 1, 1)
        self.setAsHomeButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.setAsHomeButton.setMinimumSize(QtCore.QSize(30, 30))
        self.setAsHomeButton.setMaximumSize(QtCore.QSize(30, 30))
        self.setAsHomeButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/GUI_icons/setHome.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setAsHomeButton.setIcon(icon2)
        self.setAsHomeButton.setIconSize(QtCore.QSize(30, 30))
        self.setAsHomeButton.setObjectName("setAsHomeButton")
        self.originLayout.addWidget(self.setAsHomeButton, 0, 0, 1, 1)
        self.layoutWidget5 = QtWidgets.QWidget(self.manualOperation)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 129, 131, 64))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.presetLayout = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.presetLayout.setContentsMargins(0, 0, 0, 0)
        self.presetLayout.setObjectName("presetLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.presetLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.presetLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.presetLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.presetLabel.setFont(font)
        self.presetLabel.setObjectName("presetLabel")
        self.horizontalLayout_5.addWidget(self.presetLabel)
        self.presetMotorCombo = QtWidgets.QComboBox(self.layoutWidget5)
        self.presetMotorCombo.setMaximumSize(QtCore.QSize(70, 16777215))
        self.presetMotorCombo.setObjectName("presetMotorCombo")
        self.presetMotorCombo.addItem("")
        self.presetMotorCombo.addItem("")
        self.presetMotorCombo.addItem("")
        self.horizontalLayout_5.addWidget(self.presetMotorCombo)
        self.presetLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.presetValue = QtWidgets.QLineEdit(self.layoutWidget5)
        self.presetValue.setMinimumSize(QtCore.QSize(0, 0))
        self.presetValue.setObjectName("presetValue")
        self.horizontalLayout_3.addWidget(self.presetValue)
        self.unitLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.unitLabel.setMinimumSize(QtCore.QSize(30, 0))
        self.unitLabel.setObjectName("unitLabel")
        self.horizontalLayout_3.addWidget(self.unitLabel)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.presetExe = QtWidgets.QPushButton(self.layoutWidget5)
        self.presetExe.setMaximumSize(QtCore.QSize(24, 16777215))
        self.presetExe.setText("")
        self.presetExe.setIcon(icon)
        self.presetExe.setAutoDefault(True)
        self.presetExe.setObjectName("presetExe")
        self.horizontalLayout_4.addWidget(self.presetExe)
        self.presetLayout.addLayout(self.horizontalLayout_4)
        self.layoutWidget6 = QtWidgets.QWidget(self.manualOperation)
        self.layoutWidget6.setGeometry(QtCore.QRect(184, 130, 299, 54))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.saveLayput = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.saveLayput.setContentsMargins(0, 0, 0, 0)
        self.saveLayput.setSpacing(0)
        self.saveLayput.setObjectName("saveLayput")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.savedPositionslabel = QtWidgets.QLabel(self.layoutWidget6)
        self.savedPositionslabel.setObjectName("savedPositionslabel")
        self.horizontalLayout_8.addWidget(self.savedPositionslabel)
        self.saveButton = QtWidgets.QPushButton(self.layoutWidget6)
        self.saveButton.setMaximumSize(QtCore.QSize(50, 24))
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_8.addWidget(self.saveButton)
        self.GoButton = QtWidgets.QPushButton(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GoButton.sizePolicy().hasHeightForWidth())
        self.GoButton.setSizePolicy(sizePolicy)
        self.GoButton.setMaximumSize(QtCore.QSize(24, 24))
        self.GoButton.setText("")
        self.GoButton.setIcon(icon)
        self.GoButton.setAutoDefault(True)
        self.GoButton.setObjectName("GoButton")
        self.horizontalLayout_8.addWidget(self.GoButton)
        self.saveLayput.addLayout(self.horizontalLayout_8)
        self.savedPosCombo = QtWidgets.QComboBox(self.layoutWidget6)
        self.savedPosCombo.setEditable(False)
        self.savedPosCombo.setCurrentText("")
        self.savedPosCombo.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.savedPosCombo.setObjectName("savedPosCombo")
        self.saveLayput.addWidget(self.savedPosCombo)
        self.initializeButton = QtWidgets.QPushButton(self.robotControl)
        self.initializeButton.setGeometry(QtCore.QRect(10, 33, 80, 25))
        self.initializeButton.setMaximumSize(QtCore.QSize(150, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(117, 231, 9))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 192, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 77, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 103, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 204, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(117, 231, 9))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 192, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 77, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 103, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 204, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 77, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(186, 189, 182))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(117, 231, 9))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 192, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 77, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 103, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 77, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 77, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.initializeButton.setPalette(palette)
        self.initializeButton.setAutoDefault(True)
        self.initializeButton.setObjectName("initializeButton")
        self.getCurrentPosButton = QtWidgets.QPushButton(self.robotControl)
        self.getCurrentPosButton.setGeometry(QtCore.QRect(380, 30, 121, 21))
        self.getCurrentPosButton.setObjectName("getCurrentPosButton")
        self.MagikEye = QtWidgets.QPushButton(self.centralwidget)
        self.MagikEye.setGeometry(QtCore.QRect(430, 10, 101, 25))
        self.MagikEye.setAutoDefault(True)
        self.MagikEye.setObjectName("MagikEye")
        self.Script_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.Script_groupBox.setGeometry(QtCore.QRect(20, 530, 511, 291))
        self.Script_groupBox.setObjectName("Script_groupBox")
        self.showScriptName_label = QtWidgets.QLabel(self.Script_groupBox)
        self.showScriptName_label.setGeometry(QtCore.QRect(10, 30, 231, 17))
        self.showScriptName_label.setObjectName("showScriptName_label")
        self.layoutWidget7 = QtWidgets.QWidget(self.Script_groupBox)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 50, 241, 26))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scriptName_label = QtWidgets.QLabel(self.layoutWidget7)
        self.scriptName_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scriptName_label.setText("")
        self.scriptName_label.setObjectName("scriptName_label")
        self.horizontalLayout_2.addWidget(self.scriptName_label)
        self.selectScript_toolButton = QtWidgets.QToolButton(self.layoutWidget7)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/GUI_icons/file_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.selectScript_toolButton.setIcon(icon3)
        self.selectScript_toolButton.setObjectName("selectScript_toolButton")
        self.horizontalLayout_2.addWidget(self.selectScript_toolButton)
        self.continueButton = QtWidgets.QPushButton(self.Script_groupBox)
        self.continueButton.setGeometry(QtCore.QRect(300, 180, 71, 24))
        self.continueButton.setObjectName("continueButton")
        self.opsToExeScript_label = QtWidgets.QLabel(self.Script_groupBox)
        self.opsToExeScript_label.setGeometry(QtCore.QRect(270, 50, 111, 17))
        self.opsToExeScript_label.setObjectName("opsToExeScript_label")
        self.showBaseFolderName_label = QtWidgets.QLabel(self.Script_groupBox)
        self.showBaseFolderName_label.setGeometry(QtCore.QRect(10, 110, 91, 17))
        self.showBaseFolderName_label.setObjectName("showBaseFolderName_label")
        self.layoutWidget_3 = QtWidgets.QWidget(self.Script_groupBox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 130, 241, 26))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.baseFolderName_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.baseFolderName_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.baseFolderName_label.setText("")
        self.baseFolderName_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.baseFolderName_label.setObjectName("baseFolderName_label")
        self.horizontalLayout_6.addWidget(self.baseFolderName_label)
        self.selectBaseFolder_toolButton = QtWidgets.QToolButton(self.layoutWidget_3)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/GUI_icons/049-folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.selectBaseFolder_toolButton.setIcon(icon4)
        self.selectBaseFolder_toolButton.setObjectName("selectBaseFolder_toolButton")
        self.horizontalLayout_6.addWidget(self.selectBaseFolder_toolButton)
        self.showSubFolderName_label = QtWidgets.QLabel(self.Script_groupBox)
        self.showSubFolderName_label.setGeometry(QtCore.QRect(10, 160, 91, 17))
        self.showSubFolderName_label.setObjectName("showSubFolderName_label")
        self.layoutWidget_5 = QtWidgets.QWidget(self.Script_groupBox)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 180, 241, 26))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.subFolderName_label = QtWidgets.QLabel(self.layoutWidget_5)
        self.subFolderName_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.subFolderName_label.setText("")
        self.subFolderName_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.subFolderName_label.setObjectName("subFolderName_label")
        self.horizontalLayout_7.addWidget(self.subFolderName_label)
        self.renewSubFolder_toolButton = QtWidgets.QToolButton(self.layoutWidget_5)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/GUI_icons/133-spinner11.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.renewSubFolder_toolButton.setIcon(icon5)
        self.renewSubFolder_toolButton.setObjectName("renewSubFolder_toolButton")
        self.horizontalLayout_7.addWidget(self.renewSubFolder_toolButton)
        self.selectSubFolder_toolButton = QtWidgets.QToolButton(self.layoutWidget_5)
        self.selectSubFolder_toolButton.setIcon(icon4)
        self.selectSubFolder_toolButton.setObjectName("selectSubFolder_toolButton")
        self.horizontalLayout_7.addWidget(self.selectSubFolder_toolButton)
        self.label = QtWidgets.QLabel(self.Script_groupBox)
        self.label.setGeometry(QtCore.QRect(270, 80, 151, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Script_groupBox)
        self.label_2.setGeometry(QtCore.QRect(270, 100, 91, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Script_groupBox)
        self.label_3.setGeometry(QtCore.QRect(390, 100, 91, 17))
        self.label_3.setObjectName("label_3")
        self.IRonMultiplier = QtWidgets.QLineEdit(self.Script_groupBox)
        self.IRonMultiplier.setGeometry(QtCore.QRect(270, 120, 111, 25))
        self.IRonMultiplier.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.IRonMultiplier.setObjectName("IRonMultiplier")
        self.IRoffMultiplier = QtWidgets.QLineEdit(self.Script_groupBox)
        self.IRoffMultiplier.setGeometry(QtCore.QRect(390, 120, 111, 25))
        self.IRoffMultiplier.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.IRoffMultiplier.setObjectName("IRoffMultiplier")
        self.numOfCommands_label = QtWidgets.QLabel(self.Script_groupBox)
        self.numOfCommands_label.setGeometry(QtCore.QRect(380, 50, 111, 17))
        self.numOfCommands_label.setObjectName("numOfCommands_label")
        self.executeScript_button = QtWidgets.QPushButton(self.Script_groupBox)
        self.executeScript_button.setGeometry(QtCore.QRect(270, 180, 24, 24))
        self.executeScript_button.setText("")
        self.executeScript_button.setIcon(icon)
        self.executeScript_button.setObjectName("executeScript_button")
        self.stopButton = QtWidgets.QPushButton(self.Script_groupBox)
        self.stopButton.setGeometry(QtCore.QRect(430, 180, 71, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 147, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 94, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 27, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 148, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 147, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 94, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 27, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 148, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(186, 189, 182))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 147, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 94, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 27, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.stopButton.setPalette(palette)
        self.stopButton.setObjectName("stopButton")
        self.layoutWidget_6 = QtWidgets.QWidget(self.Script_groupBox)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 80, 241, 27))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.scriptName_label_2 = QtWidgets.QLabel(self.layoutWidget_6)
        self.scriptName_label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scriptName_label_2.setText("")
        self.scriptName_label_2.setObjectName("scriptName_label_2")
        self.horizontalLayout_9.addWidget(self.scriptName_label_2)
        self.delete2ndScriptButton = QtWidgets.QPushButton(self.layoutWidget_6)
        self.delete2ndScriptButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.delete2ndScriptButton.setObjectName("delete2ndScriptButton")
        self.horizontalLayout_9.addWidget(self.delete2ndScriptButton)
        self.selectScript_toolButton_2 = QtWidgets.QToolButton(self.layoutWidget_6)
        self.selectScript_toolButton_2.setIcon(icon3)
        self.selectScript_toolButton_2.setObjectName("selectScript_toolButton_2")
        self.horizontalLayout_9.addWidget(self.selectScript_toolButton_2)
        self.Scripting_groupBox = QtWidgets.QFrame(self.Script_groupBox)
        self.Scripting_groupBox.setGeometry(QtCore.QRect(0, 210, 511, 80))
        self.Scripting_groupBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Scripting_groupBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Scripting_groupBox.setObjectName("Scripting_groupBox")
        self.progressLabel = QtWidgets.QLabel(self.Scripting_groupBox)
        self.progressLabel.setGeometry(QtCore.QRect(410, 20, 91, 20))
        self.progressLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.progressLabel.setObjectName("progressLabel")
        self.commandLabel = QtWidgets.QLabel(self.Scripting_groupBox)
        self.commandLabel.setGeometry(QtCore.QRect(10, 20, 121, 20))
        self.commandLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commandLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.commandLabel.setObjectName("commandLabel")
        self.ExecutingScript = QtWidgets.QLabel(self.Scripting_groupBox)
        self.ExecutingScript.setGeometry(QtCore.QRect(10, 0, 141, 20))
        self.ExecutingScript.setObjectName("ExecutingScript")
        self.progressBar = QtWidgets.QProgressBar(self.Scripting_groupBox)
        self.progressBar.setGeometry(QtCore.QRect(10, 40, 491, 30))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.viewSensorWinButton = QtWidgets.QPushButton(self.centralwidget)
        self.viewSensorWinButton.setGeometry(QtCore.QRect(310, 10, 111, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 201, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 117, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 215, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 201, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 117, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 215, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(186, 189, 182))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 201, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 117, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.viewSensorWinButton.setPalette(palette)
        self.viewSensorWinButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.viewSensorWinButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.viewSensorWinButton.setObjectName("viewSensorWinButton")
        self.IRlightControlGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.IRlightControlGroup.setGeometry(QtCore.QRect(20, 440, 511, 81))
        self.IRlightControlGroup.setObjectName("IRlightControlGroup")
        self.layoutWidget_2 = QtWidgets.QWidget(self.IRlightControlGroup)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 36, 101, 32))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.L1GridLayout = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.L1GridLayout.setContentsMargins(0, 0, 0, 0)
        self.L1GridLayout.setObjectName("L1GridLayout")
        self.L1Label = QtWidgets.QLabel(self.layoutWidget_2)
        self.L1Label.setMaximumSize(QtCore.QSize(20, 16777215))
        self.L1Label.setObjectName("L1Label")
        self.L1GridLayout.addWidget(self.L1Label, 0, 0, 1, 1)
        self.onL1Button = QtWidgets.QPushButton(self.layoutWidget_2)
        self.onL1Button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.onL1Button.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/GUI_icons/lightON.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.onL1Button.setIcon(icon6)
        self.onL1Button.setCheckable(True)
        self.onL1Button.setChecked(False)
        self.onL1Button.setAutoExclusive(True)
        self.onL1Button.setObjectName("onL1Button")
        self.L1GridLayout.addWidget(self.onL1Button, 0, 1, 1, 1)
        self.offL1Button = QtWidgets.QPushButton(self.layoutWidget_2)
        self.offL1Button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.offL1Button.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/GUI_icons/lightOFF.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.offL1Button.setIcon(icon7)
        self.offL1Button.setCheckable(True)
        self.offL1Button.setChecked(False)
        self.offL1Button.setAutoExclusive(True)
        self.offL1Button.setObjectName("offL1Button")
        self.L1GridLayout.addWidget(self.offL1Button, 0, 2, 1, 1)
        self.layoutWidget_4 = QtWidgets.QWidget(self.IRlightControlGroup)
        self.layoutWidget_4.setGeometry(QtCore.QRect(120, 36, 101, 32))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.L2GridLayout = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.L2GridLayout.setContentsMargins(0, 0, 0, 0)
        self.L2GridLayout.setObjectName("L2GridLayout")
        self.L2Label = QtWidgets.QLabel(self.layoutWidget_4)
        self.L2Label.setMaximumSize(QtCore.QSize(20, 16777215))
        self.L2Label.setObjectName("L2Label")
        self.L2GridLayout.addWidget(self.L2Label, 0, 0, 1, 1)
        self.onL2Button = QtWidgets.QPushButton(self.layoutWidget_4)
        self.onL2Button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.onL2Button.setText("")
        self.onL2Button.setIcon(icon6)
        self.onL2Button.setCheckable(True)
        self.onL2Button.setAutoExclusive(True)
        self.onL2Button.setObjectName("onL2Button")
        self.L2GridLayout.addWidget(self.onL2Button, 0, 1, 1, 1)
        self.offL2Button = QtWidgets.QPushButton(self.layoutWidget_4)
        self.offL2Button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.offL2Button.setText("")
        self.offL2Button.setIcon(icon7)
        self.offL2Button.setCheckable(True)
        self.offL2Button.setAutoExclusive(True)
        self.offL2Button.setObjectName("offL2Button")
        self.L2GridLayout.addWidget(self.offL2Button, 0, 2, 1, 1)
        self.IRstateLabel = QtWidgets.QLabel(self.IRlightControlGroup)
        self.IRstateLabel.setGeometry(QtCore.QRect(230, 26, 271, 51))
        self.IRstateLabel.setWordWrap(True)
        self.IRstateLabel.setObjectName("IRstateLabel")
        self.selectMachineFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectMachineFileButton.setGeometry(QtCore.QRect(200, 10, 91, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(117, 231, 9))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 192, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 77, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 103, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 204, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(117, 231, 9))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 192, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 77, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 103, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 204, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 77, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(186, 189, 182))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(117, 231, 9))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 192, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 77, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 103, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 77, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 77, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.selectMachineFileButton.setPalette(palette)
        self.selectMachineFileButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.selectMachineFileButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.selectMachineFileButton.setObjectName("selectMachineFileButton")
        self.machineFileName_label = QtWidgets.QLabel(self.centralwidget)
        self.machineFileName_label.setGeometry(QtCore.QRect(26, 10, 171, 25))
        self.machineFileName_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.machineFileName_label.setText("")
        self.machineFileName_label.setObjectName("machineFileName_label")
        mainwindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainwindow)
        self.statusbar.setObjectName("statusbar")
        mainwindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 552, 22))
        self.menubar.setObjectName("menubar")
        mainwindow.setMenuBar(self.menubar)

        self.retranslateUi(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)
        mainwindow.setTabOrder(self.initializeButton, self.sliderOriginButton)
        mainwindow.setTabOrder(self.sliderOriginButton, self.MagikEye)
        mainwindow.setTabOrder(self.MagikEye, self.sliderPosSpin)
        mainwindow.setTabOrder(self.sliderPosSpin, self.panPosSpin)
        mainwindow.setTabOrder(self.panPosSpin, self.tiltPosSpin)
        mainwindow.setTabOrder(self.tiltPosSpin, self.sliderMoveExe)
        mainwindow.setTabOrder(self.sliderMoveExe, self.panMoveExe)
        mainwindow.setTabOrder(self.panMoveExe, self.tiltMoveExe)
        mainwindow.setTabOrder(self.tiltMoveExe, self.sliderSpeedSpin)
        mainwindow.setTabOrder(self.sliderSpeedSpin, self.panSpeedSpin)
        mainwindow.setTabOrder(self.panSpeedSpin, self.tiltSpeedSpin)
        mainwindow.setTabOrder(self.tiltSpeedSpin, self.presetMotorCombo)
        mainwindow.setTabOrder(self.presetMotorCombo, self.presetValue)
        mainwindow.setTabOrder(self.presetValue, self.presetExe)
        mainwindow.setTabOrder(self.presetExe, self.Settings)
        mainwindow.setTabOrder(self.Settings, self.freeButton)
        mainwindow.setTabOrder(self.freeButton, self.executeScript_button)
        mainwindow.setTabOrder(self.executeScript_button, self.saveButton)
        mainwindow.setTabOrder(self.saveButton, self.savedPosCombo)
        mainwindow.setTabOrder(self.savedPosCombo, self.rebootButton)
        mainwindow.setTabOrder(self.rebootButton, self.GoButton)
        mainwindow.setTabOrder(self.GoButton, self.goHomeButton)
        mainwindow.setTabOrder(self.goHomeButton, self.setAsHomeButton)
        mainwindow.setTabOrder(self.setAsHomeButton, self.selectScript_toolButton)
        mainwindow.setTabOrder(self.selectScript_toolButton, self.continueButton)
        mainwindow.setTabOrder(self.continueButton, self.selectBaseFolder_toolButton)
        mainwindow.setTabOrder(self.selectBaseFolder_toolButton, self.selectSubFolder_toolButton)
        mainwindow.setTabOrder(self.selectSubFolder_toolButton, self.viewSensorWinButton)
        mainwindow.setTabOrder(self.viewSensorWinButton, self.onL1Button)
        mainwindow.setTabOrder(self.onL1Button, self.offL1Button)
        mainwindow.setTabOrder(self.offL1Button, self.onL2Button)
        mainwindow.setTabOrder(self.onL2Button, self.offL2Button)
        mainwindow.setTabOrder(self.offL2Button, self.renewSubFolder_toolButton)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "MkECTL"))
        self.robotControl.setTitle(_translate("mainwindow", "Robot Control"))
        self.initializeProgressLabel.setText(_translate("mainwindow", "Initializing motors..."))
        self.Settings.setTitle(_translate("mainwindow", "Settings"))
        self.sliderSpeedLabel.setText(_translate("mainwindow", "Slider"))
        self.panSpeedLabel.setText(_translate("mainwindow", "Pan"))
        self.tiltSpeedLabel.setText(_translate("mainwindow", "Tilt"))
        self.radpersec.setText(_translate("mainwindow", "rad/s"))
        self.radpersec_2.setText(_translate("mainwindow", "rad/s"))
        self.radpersec_3.setText(_translate("mainwindow", "rad/s"))
        self.setSpeedLabel.setText(_translate("mainwindow", "Speed"))
        self.detailedSettingsButton.setText(_translate("mainwindow", "..."))
        self.currentPoslabel.setText(_translate("mainwindow", "Current Pos."))
        self.currentSliderLabel.setText(_translate("mainwindow", "slider"))
        self.sliderCurrentPos.setText(_translate("mainwindow", "0"))
        self.currentPanLabel.setText(_translate("mainwindow", "pan"))
        self.panCurrentPos.setText(_translate("mainwindow", "0"))
        self.currentTiltLabel.setText(_translate("mainwindow", "tilt"))
        self.tiltCurrentPos.setText(_translate("mainwindow", "0"))
        self.manualOperation.setTitle(_translate("mainwindow", "Manual Operation"))
        self.sliderOriginButton.setText(_translate("mainwindow", "Set Slider Origin"))
        self.freeButton.setText(_translate("mainwindow", "FREE all motors"))
        self.rebootButton.setText(_translate("mainwindow", "REBOOT all motors"))
        self.panLabel.setText(_translate("mainwindow", "Pan [-360 to 360 deg]"))
        self.sliderLabel.setText(_translate("mainwindow", "Slider [-4000 to 4000 mm]"))
        self.tiltLabel.setText(_translate("mainwindow", "Tilt [-360 to 360 deg]"))
        self.originLabel.setText(_translate("mainwindow", "Origin"))
        self.presetLabel.setText(_translate("mainwindow", "Preset"))
        self.presetMotorCombo.setItemText(0, _translate("mainwindow", "slider"))
        self.presetMotorCombo.setItemText(1, _translate("mainwindow", "pan"))
        self.presetMotorCombo.setItemText(2, _translate("mainwindow", "tilt"))
        self.unitLabel.setText(_translate("mainwindow", "mm"))
        self.savedPositionslabel.setText(_translate("mainwindow", "Saved Positions [slider pan tilt]"))
        self.saveButton.setText(_translate("mainwindow", "Save"))
        self.initializeButton.setText(_translate("mainwindow", "Initialize"))
        self.getCurrentPosButton.setText(_translate("mainwindow", "Get Current Pos."))
        self.MagikEye.setText(_translate("mainwindow", "●MagikEye●"))
        self.Script_groupBox.setTitle(_translate("mainwindow", "Script"))
        self.showScriptName_label.setText(_translate("mainwindow", "Script name (2nd one is optional):"))
        self.selectScript_toolButton.setText(_translate("mainwindow", "..."))
        self.continueButton.setText(_translate("mainwindow", "Continue"))
        self.opsToExeScript_label.setText(_translate("mainwindow", "Ops to execute:"))
        self.showBaseFolderName_label.setText(_translate("mainwindow", "Base folder:"))
        self.selectBaseFolder_toolButton.setText(_translate("mainwindow", "..."))
        self.showSubFolderName_label.setText(_translate("mainwindow", "Sub folder:"))
        self.renewSubFolder_toolButton.setText(_translate("mainwindow", "..."))
        self.selectSubFolder_toolButton.setText(_translate("mainwindow", "..."))
        self.label.setText(_translate("mainwindow", "Exposure multiplier"))
        self.label_2.setText(_translate("mainwindow", "IR light - ON"))
        self.label_3.setText(_translate("mainwindow", "IR light - OFF"))
        self.IRonMultiplier.setText(_translate("mainwindow", "1.00"))
        self.IRoffMultiplier.setText(_translate("mainwindow", "1.00"))
        self.numOfCommands_label.setText(_translate("mainwindow", " -"))
        self.stopButton.setText(_translate("mainwindow", "Stop"))
        self.delete2ndScriptButton.setText(_translate("mainwindow", "Del"))
        self.selectScript_toolButton_2.setText(_translate("mainwindow", "..."))
        self.progressLabel.setText(_translate("mainwindow", "progress"))
        self.commandLabel.setText(_translate("mainwindow", "command"))
        self.ExecutingScript.setText(_translate("mainwindow", "Script Progress"))
        self.viewSensorWinButton.setText(_translate("mainwindow", "Sensor Window"))
        self.IRlightControlGroup.setTitle(_translate("mainwindow", "IR Light Control"))
        self.L1Label.setText(_translate("mainwindow", "L1"))
        self.L2Label.setText(_translate("mainwindow", "L2"))
        self.IRstateLabel.setText(_translate("mainwindow", "Not connected"))
        self.selectMachineFileButton.setText(_translate("mainwindow", "Machine File"))
from MyDoubleSpinBox import MyDoubleSpinBox
import resources_rc
