# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/magikeye/bin/MkECTL/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(673, 573)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        mainwindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.robotControl = QtWidgets.QGroupBox(self.centralwidget)
        self.robotControl.setEnabled(True)
        self.robotControl.setGeometry(QtCore.QRect(20, 30, 631, 371))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.robotControl.sizePolicy().hasHeightForWidth())
        self.robotControl.setSizePolicy(sizePolicy)
        self.robotControl.setObjectName("robotControl")
        self.initializeProgressLabel = QtWidgets.QLabel(self.robotControl)
        self.initializeProgressLabel.setEnabled(False)
        self.initializeProgressLabel.setGeometry(QtCore.QRect(9, 70, 141, 17))
        self.initializeProgressLabel.setObjectName("initializeProgressLabel")
        self.initializeProgressBar = QtWidgets.QProgressBar(self.robotControl)
        self.initializeProgressBar.setEnabled(False)
        self.initializeProgressBar.setGeometry(QtCore.QRect(9, 90, 118, 23))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(False)
        font.setWeight(50)
        self.initializeProgressBar.setFont(font)
        self.initializeProgressBar.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.initializeProgressBar.setProperty("value", 0)
        self.initializeProgressBar.setObjectName("initializeProgressBar")
        self.Settings = QtWidgets.QGroupBox(self.robotControl)
        self.Settings.setEnabled(True)
        self.Settings.setGeometry(QtCore.QRect(20, 200, 441, 161))
        self.Settings.setAutoFillBackground(False)
        self.Settings.setFlat(False)
        self.Settings.setCheckable(True)
        self.Settings.setChecked(True)
        self.Settings.setObjectName("Settings")
        self.layoutWidget = QtWidgets.QWidget(self.Settings)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 50, 181, 94))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sliderSpeedLabel = QtWidgets.QLabel(self.layoutWidget)
        self.sliderSpeedLabel.setObjectName("sliderSpeedLabel")
        self.verticalLayout_2.addWidget(self.sliderSpeedLabel)
        self.panSpeedLabel = QtWidgets.QLabel(self.layoutWidget)
        self.panSpeedLabel.setObjectName("panSpeedLabel")
        self.verticalLayout_2.addWidget(self.panSpeedLabel)
        self.tiltSpeedLabel = QtWidgets.QLabel(self.layoutWidget)
        self.tiltSpeedLabel.setObjectName("tiltSpeedLabel")
        self.verticalLayout_2.addWidget(self.tiltSpeedLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sliderSpeedSpin = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.sliderSpeedSpin.setDecimals(1)
        self.sliderSpeedSpin.setProperty("value", 20.0)
        self.sliderSpeedSpin.setObjectName("sliderSpeedSpin")
        self.verticalLayout_3.addWidget(self.sliderSpeedSpin)
        self.panSpeedSpin = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.panSpeedSpin.setDecimals(1)
        self.panSpeedSpin.setProperty("value", 5.0)
        self.panSpeedSpin.setObjectName("panSpeedSpin")
        self.verticalLayout_3.addWidget(self.panSpeedSpin)
        self.tiltSpeedSpin = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.tiltSpeedSpin.setDecimals(1)
        self.tiltSpeedSpin.setProperty("value", 5.0)
        self.tiltSpeedSpin.setObjectName("tiltSpeedSpin")
        self.verticalLayout_3.addWidget(self.tiltSpeedSpin)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radpersec = QtWidgets.QLabel(self.layoutWidget)
        self.radpersec.setMinimumSize(QtCore.QSize(40, 0))
        self.radpersec.setObjectName("radpersec")
        self.verticalLayout_4.addWidget(self.radpersec)
        self.radpersec_2 = QtWidgets.QLabel(self.layoutWidget)
        self.radpersec_2.setMinimumSize(QtCore.QSize(40, 0))
        self.radpersec_2.setObjectName("radpersec_2")
        self.verticalLayout_4.addWidget(self.radpersec_2)
        self.radpersec_3 = QtWidgets.QLabel(self.layoutWidget)
        self.radpersec_3.setMinimumSize(QtCore.QSize(40, 0))
        self.radpersec_3.setObjectName("radpersec_3")
        self.verticalLayout_4.addWidget(self.radpersec_3)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.setSpeedLabel = QtWidgets.QLabel(self.Settings)
        self.setSpeedLabel.setGeometry(QtCore.QRect(20, 30, 100, 16))
        self.setSpeedLabel.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.setSpeedLabel.setFont(font)
        self.setSpeedLabel.setObjectName("setSpeedLabel")
        self.presetLabel = QtWidgets.QLabel(self.Settings)
        self.presetLabel.setGeometry(QtCore.QRect(220, 30, 69, 20))
        self.presetLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.presetLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.presetLabel.setFont(font)
        self.presetLabel.setObjectName("presetLabel")
        self.layoutWidget1 = QtWidgets.QWidget(self.Settings)
        self.layoutWidget1.setGeometry(QtCore.QRect(220, 110, 108, 46))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.homeGridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.homeGridLayout.setContentsMargins(0, 0, 0, 0)
        self.homeGridLayout.setObjectName("homeGridLayout")
        self.setAsHomeButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.setAsHomeButton.setMinimumSize(QtCore.QSize(30, 30))
        self.setAsHomeButton.setMaximumSize(QtCore.QSize(30, 30))
        self.setAsHomeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/GUI_icons/setHome.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setAsHomeButton.setIcon(icon)
        self.setAsHomeButton.setIconSize(QtCore.QSize(30, 30))
        self.setAsHomeButton.setObjectName("setAsHomeButton")
        self.homeGridLayout.addWidget(self.setAsHomeButton, 0, 0, 1, 1)
        self.goHomeButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.goHomeButton.setMinimumSize(QtCore.QSize(30, 30))
        self.goHomeButton.setMaximumSize(QtCore.QSize(30, 30))
        self.goHomeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/GUI_icons/goTo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.goHomeButton.setIcon(icon1)
        self.goHomeButton.setIconSize(QtCore.QSize(30, 30))
        self.goHomeButton.setObjectName("goHomeButton")
        self.homeGridLayout.addWidget(self.goHomeButton, 0, 1, 1, 1)
        self.originLabel = QtWidgets.QLabel(self.Settings)
        self.originLabel.setGeometry(QtCore.QRect(220, 90, 69, 20))
        self.originLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.originLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.originLabel.setFont(font)
        self.originLabel.setObjectName("originLabel")
        self.layoutWidget2 = QtWidgets.QWidget(self.Settings)
        self.layoutWidget2.setGeometry(QtCore.QRect(220, 50, 211, 38))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.presetMotorCombo = QtWidgets.QComboBox(self.layoutWidget2)
        self.presetMotorCombo.setMaximumSize(QtCore.QSize(70, 16777215))
        self.presetMotorCombo.setObjectName("presetMotorCombo")
        self.presetMotorCombo.addItem("")
        self.presetMotorCombo.addItem("")
        self.presetMotorCombo.addItem("")
        self.horizontalLayout_4.addWidget(self.presetMotorCombo)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.presetValue = QtWidgets.QLineEdit(self.layoutWidget2)
        self.presetValue.setMinimumSize(QtCore.QSize(0, 0))
        self.presetValue.setObjectName("presetValue")
        self.horizontalLayout_3.addWidget(self.presetValue)
        self.unitLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.unitLabel.setMinimumSize(QtCore.QSize(30, 0))
        self.unitLabel.setObjectName("unitLabel")
        self.horizontalLayout_3.addWidget(self.unitLabel)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.presetExe = QtWidgets.QPushButton(self.layoutWidget2)
        self.presetExe.setMaximumSize(QtCore.QSize(24, 16777215))
        self.presetExe.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/GUI_icons/exec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.presetExe.setIcon(icon2)
        self.presetExe.setAutoDefault(True)
        self.presetExe.setObjectName("presetExe")
        self.horizontalLayout_4.addWidget(self.presetExe)
        self.layoutWidget3 = QtWidgets.QWidget(self.robotControl)
        self.layoutWidget3.setGeometry(QtCore.QRect(480, 220, 131, 101))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.currentPoslabel = QtWidgets.QLabel(self.layoutWidget3)
        self.currentPoslabel.setAlignment(QtCore.Qt.AlignCenter)
        self.currentPoslabel.setObjectName("currentPoslabel")
        self.gridLayout.addWidget(self.currentPoslabel, 0, 1, 1, 1)
        self.currentSliderLabel = QtWidgets.QLabel(self.layoutWidget3)
        self.currentSliderLabel.setObjectName("currentSliderLabel")
        self.gridLayout.addWidget(self.currentSliderLabel, 1, 0, 1, 1)
        self.sliderCurrentPos = QtWidgets.QLabel(self.layoutWidget3)
        self.sliderCurrentPos.setAlignment(QtCore.Qt.AlignCenter)
        self.sliderCurrentPos.setObjectName("sliderCurrentPos")
        self.gridLayout.addWidget(self.sliderCurrentPos, 1, 1, 1, 1)
        self.currentPanLabel = QtWidgets.QLabel(self.layoutWidget3)
        self.currentPanLabel.setObjectName("currentPanLabel")
        self.gridLayout.addWidget(self.currentPanLabel, 2, 0, 1, 1)
        self.panCurrentPos = QtWidgets.QLabel(self.layoutWidget3)
        self.panCurrentPos.setAlignment(QtCore.Qt.AlignCenter)
        self.panCurrentPos.setObjectName("panCurrentPos")
        self.gridLayout.addWidget(self.panCurrentPos, 2, 1, 1, 1)
        self.currentTiltLabel = QtWidgets.QLabel(self.layoutWidget3)
        self.currentTiltLabel.setObjectName("currentTiltLabel")
        self.gridLayout.addWidget(self.currentTiltLabel, 3, 0, 1, 1)
        self.tiltCurrentPos = QtWidgets.QLabel(self.layoutWidget3)
        self.tiltCurrentPos.setAlignment(QtCore.Qt.AlignCenter)
        self.tiltCurrentPos.setObjectName("tiltCurrentPos")
        self.gridLayout.addWidget(self.tiltCurrentPos, 3, 1, 1, 1)
        self.motorConfigration = QtWidgets.QGroupBox(self.robotControl)
        self.motorConfigration.setGeometry(QtCore.QRect(150, 30, 471, 181))
        self.motorConfigration.setCheckable(False)
        self.motorConfigration.setObjectName("motorConfigration")
        self.saveButton = QtWidgets.QPushButton(self.motorConfigration)
        self.saveButton.setGeometry(QtCore.QRect(400, 130, 51, 21))
        self.saveButton.setObjectName("saveButton")
        self.savedPosCombo = QtWidgets.QComboBox(self.motorConfigration)
        self.savedPosCombo.setGeometry(QtCore.QRect(160, 150, 181, 25))
        self.savedPosCombo.setEditable(False)
        self.savedPosCombo.setCurrentText("")
        self.savedPosCombo.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.savedPosCombo.setObjectName("savedPosCombo")
        self.layoutWidget4 = QtWidgets.QWidget(self.motorConfigration)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 30, 141, 89))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sliderOriginButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.sliderOriginButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.sliderOriginButton.setAutoDefault(True)
        self.sliderOriginButton.setObjectName("sliderOriginButton")
        self.verticalLayout.addWidget(self.sliderOriginButton)
        self.freeButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.freeButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.freeButton.setAutoDefault(True)
        self.freeButton.setObjectName("freeButton")
        self.verticalLayout.addWidget(self.freeButton)
        self.rebootButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.rebootButton.setMinimumSize(QtCore.QSize(50, 0))
        self.rebootButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.rebootButton.setAutoDefault(True)
        self.rebootButton.setDefault(False)
        self.rebootButton.setFlat(False)
        self.rebootButton.setObjectName("rebootButton")
        self.verticalLayout.addWidget(self.rebootButton)
        self.layoutWidget5 = QtWidgets.QWidget(self.motorConfigration)
        self.layoutWidget5.setGeometry(QtCore.QRect(160, 30, 297, 92))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.robotControlLayout = QtWidgets.QGridLayout(self.layoutWidget5)
        self.robotControlLayout.setContentsMargins(0, 0, 0, 0)
        self.robotControlLayout.setObjectName("robotControlLayout")
        self.panLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.panLabel.setObjectName("panLabel")
        self.robotControlLayout.addWidget(self.panLabel, 1, 0, 1, 1)
        self.tiltMoveExe = QtWidgets.QPushButton(self.layoutWidget5)
        self.tiltMoveExe.setMaximumSize(QtCore.QSize(24, 16777215))
        self.tiltMoveExe.setText("")
        self.tiltMoveExe.setIcon(icon2)
        self.tiltMoveExe.setAutoDefault(True)
        self.tiltMoveExe.setObjectName("tiltMoveExe")
        self.robotControlLayout.addWidget(self.tiltMoveExe, 2, 2, 1, 1)
        self.tiltPosSpin = MyDoubleSpinBox(self.layoutWidget5)
        self.tiltPosSpin.setDecimals(2)
        self.tiltPosSpin.setMinimum(-180.0)
        self.tiltPosSpin.setMaximum(180.0)
        self.tiltPosSpin.setSingleStep(0.1)
        self.tiltPosSpin.setObjectName("tiltPosSpin")
        self.robotControlLayout.addWidget(self.tiltPosSpin, 2, 1, 1, 1)
        self.sliderLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.sliderLabel.setObjectName("sliderLabel")
        self.robotControlLayout.addWidget(self.sliderLabel, 0, 0, 1, 1)
        self.panMoveExe = QtWidgets.QPushButton(self.layoutWidget5)
        self.panMoveExe.setMaximumSize(QtCore.QSize(24, 16777215))
        self.panMoveExe.setText("")
        self.panMoveExe.setIcon(icon2)
        self.panMoveExe.setAutoDefault(True)
        self.panMoveExe.setObjectName("panMoveExe")
        self.robotControlLayout.addWidget(self.panMoveExe, 1, 2, 1, 1)
        self.sliderMoveExe = QtWidgets.QPushButton(self.layoutWidget5)
        self.sliderMoveExe.setMaximumSize(QtCore.QSize(24, 16777215))
        self.sliderMoveExe.setText("")
        self.sliderMoveExe.setIcon(icon2)
        self.sliderMoveExe.setAutoDefault(True)
        self.sliderMoveExe.setObjectName("sliderMoveExe")
        self.robotControlLayout.addWidget(self.sliderMoveExe, 0, 2, 1, 1)
        self.panPosSpin = MyDoubleSpinBox(self.layoutWidget5)
        self.panPosSpin.setDecimals(2)
        self.panPosSpin.setMinimum(-180.0)
        self.panPosSpin.setMaximum(180.0)
        self.panPosSpin.setSingleStep(0.1)
        self.panPosSpin.setObjectName("panPosSpin")
        self.robotControlLayout.addWidget(self.panPosSpin, 1, 1, 1, 1)
        self.tiltLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.tiltLabel.setObjectName("tiltLabel")
        self.robotControlLayout.addWidget(self.tiltLabel, 2, 0, 1, 1)
        self.sliderPosSpin = MyDoubleSpinBox(self.layoutWidget5)
        self.sliderPosSpin.setDecimals(2)
        self.sliderPosSpin.setMinimum(-4000.0)
        self.sliderPosSpin.setMaximum(4000.0)
        self.sliderPosSpin.setSingleStep(5.0)
        self.sliderPosSpin.setObjectName("sliderPosSpin")
        self.robotControlLayout.addWidget(self.sliderPosSpin, 0, 1, 1, 1)
        self.savedPositionslabel = QtWidgets.QLabel(self.motorConfigration)
        self.savedPositionslabel.setGeometry(QtCore.QRect(160, 130, 211, 16))
        self.savedPositionslabel.setObjectName("savedPositionslabel")
        self.GoButton = QtWidgets.QPushButton(self.motorConfigration)
        self.GoButton.setGeometry(QtCore.QRect(350, 150, 24, 24))
        self.GoButton.setMaximumSize(QtCore.QSize(24, 16777215))
        self.GoButton.setText("")
        self.GoButton.setIcon(icon2)
        self.GoButton.setAutoDefault(True)
        self.GoButton.setObjectName("GoButton")
        self.initializeButton = QtWidgets.QPushButton(self.robotControl)
        self.initializeButton.setGeometry(QtCore.QRect(10, 33, 80, 25))
        self.initializeButton.setMaximumSize(QtCore.QSize(150, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(117, 231, 9))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 192, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 77, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 103, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 204, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(117, 231, 9))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 192, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 77, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 103, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 204, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 77, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(117, 231, 9))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 192, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 77, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 103, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 77, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 77, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.initializeButton.setPalette(palette)
        self.initializeButton.setAutoDefault(True)
        self.initializeButton.setObjectName("initializeButton")
        self.MagikEye = QtWidgets.QPushButton(self.centralwidget)
        self.MagikEye.setGeometry(QtCore.QRect(540, 10, 101, 25))
        self.MagikEye.setAutoDefault(True)
        self.MagikEye.setObjectName("MagikEye")
        self.Script_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.Script_groupBox.setGeometry(QtCore.QRect(270, 410, 331, 111))
        self.Script_groupBox.setObjectName("Script_groupBox")
        self.showScriptName_label = QtWidgets.QLabel(self.Script_groupBox)
        self.showScriptName_label.setGeometry(QtCore.QRect(10, 30, 91, 17))
        self.showScriptName_label.setObjectName("showScriptName_label")
        self.executeScript_button = QtWidgets.QPushButton(self.Script_groupBox)
        self.executeScript_button.setGeometry(QtCore.QRect(210, 80, 24, 24))
        self.executeScript_button.setText("")
        self.executeScript_button.setIcon(icon2)
        self.executeScript_button.setObjectName("executeScript_button")
        self.layoutWidget6 = QtWidgets.QWidget(self.Script_groupBox)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 50, 311, 26))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scriptName_label = QtWidgets.QLabel(self.layoutWidget6)
        self.scriptName_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scriptName_label.setText("")
        self.scriptName_label.setObjectName("scriptName_label")
        self.horizontalLayout_2.addWidget(self.scriptName_label)
        self.selectScript_toolButton = QtWidgets.QToolButton(self.layoutWidget6)
        self.selectScript_toolButton.setObjectName("selectScript_toolButton")
        self.horizontalLayout_2.addWidget(self.selectScript_toolButton)
        self.continueButton = QtWidgets.QPushButton(self.Script_groupBox)
        self.continueButton.setGeometry(QtCore.QRect(118, 80, 91, 24))
        self.continueButton.setObjectName("continueButton")
        self.opsToExeScript_label = QtWidgets.QLabel(self.Script_groupBox)
        self.opsToExeScript_label.setGeometry(QtCore.QRect(10, 80, 121, 17))
        self.opsToExeScript_label.setObjectName("opsToExeScript_label")
        self.viewSensorWinButton = QtWidgets.QPushButton(self.centralwidget)
        self.viewSensorWinButton.setGeometry(QtCore.QRect(410, 10, 121, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 201, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 117, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 215, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 201, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 117, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 215, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 201, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 117, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.viewSensorWinButton.setPalette(palette)
        self.viewSensorWinButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.viewSensorWinButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.viewSensorWinButton.setObjectName("viewSensorWinButton")
        self.laserControlGroup_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.laserControlGroup_2.setGeometry(QtCore.QRect(20, 410, 231, 111))
        self.laserControlGroup_2.setObjectName("laserControlGroup_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.laserControlGroup_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 30, 101, 32))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.L1GridLayout = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.L1GridLayout.setContentsMargins(0, 0, 0, 0)
        self.L1GridLayout.setObjectName("L1GridLayout")
        self.L1Label = QtWidgets.QLabel(self.layoutWidget_2)
        self.L1Label.setMaximumSize(QtCore.QSize(20, 16777215))
        self.L1Label.setObjectName("L1Label")
        self.L1GridLayout.addWidget(self.L1Label, 0, 0, 1, 1)
        self.onL1Button = QtWidgets.QPushButton(self.layoutWidget_2)
        self.onL1Button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.onL1Button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/GUI_icons/lightON.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.onL1Button.setIcon(icon3)
        self.onL1Button.setObjectName("onL1Button")
        self.L1GridLayout.addWidget(self.onL1Button, 0, 1, 1, 1)
        self.offL1Button = QtWidgets.QPushButton(self.layoutWidget_2)
        self.offL1Button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.offL1Button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/GUI_icons/lightOFF.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.offL1Button.setIcon(icon4)
        self.offL1Button.setObjectName("offL1Button")
        self.L1GridLayout.addWidget(self.offL1Button, 0, 2, 1, 1)
        self.layoutWidget_4 = QtWidgets.QWidget(self.laserControlGroup_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(120, 30, 101, 32))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.L2GridLayout = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.L2GridLayout.setContentsMargins(0, 0, 0, 0)
        self.L2GridLayout.setObjectName("L2GridLayout")
        self.L2Label = QtWidgets.QLabel(self.layoutWidget_4)
        self.L2Label.setMaximumSize(QtCore.QSize(20, 16777215))
        self.L2Label.setObjectName("L2Label")
        self.L2GridLayout.addWidget(self.L2Label, 0, 0, 1, 1)
        self.onL2Button = QtWidgets.QPushButton(self.layoutWidget_4)
        self.onL2Button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.onL2Button.setText("")
        self.onL2Button.setIcon(icon3)
        self.onL2Button.setObjectName("onL2Button")
        self.L2GridLayout.addWidget(self.onL2Button, 0, 1, 1, 1)
        self.offL2Button = QtWidgets.QPushButton(self.layoutWidget_4)
        self.offL2Button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.offL2Button.setText("")
        self.offL2Button.setIcon(icon4)
        self.offL2Button.setObjectName("offL2Button")
        self.L2GridLayout.addWidget(self.offL2Button, 0, 2, 1, 1)
        self.IRstateLabel = QtWidgets.QLabel(self.laserControlGroup_2)
        self.IRstateLabel.setGeometry(QtCore.QRect(10, 70, 211, 31))
        self.IRstateLabel.setWordWrap(True)
        self.IRstateLabel.setObjectName("IRstateLabel")
        mainwindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainwindow)
        self.statusbar.setObjectName("statusbar")
        mainwindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 22))
        self.menubar.setObjectName("menubar")
        mainwindow.setMenuBar(self.menubar)

        self.retranslateUi(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)
        mainwindow.setTabOrder(self.initializeButton, self.sliderOriginButton)
        mainwindow.setTabOrder(self.sliderOriginButton, self.MagikEye)
        mainwindow.setTabOrder(self.MagikEye, self.sliderPosSpin)
        mainwindow.setTabOrder(self.sliderPosSpin, self.panPosSpin)
        mainwindow.setTabOrder(self.panPosSpin, self.tiltPosSpin)
        mainwindow.setTabOrder(self.tiltPosSpin, self.sliderMoveExe)
        mainwindow.setTabOrder(self.sliderMoveExe, self.panMoveExe)
        mainwindow.setTabOrder(self.panMoveExe, self.tiltMoveExe)
        mainwindow.setTabOrder(self.tiltMoveExe, self.sliderSpeedSpin)
        mainwindow.setTabOrder(self.sliderSpeedSpin, self.panSpeedSpin)
        mainwindow.setTabOrder(self.panSpeedSpin, self.tiltSpeedSpin)
        mainwindow.setTabOrder(self.tiltSpeedSpin, self.presetMotorCombo)
        mainwindow.setTabOrder(self.presetMotorCombo, self.presetValue)
        mainwindow.setTabOrder(self.presetValue, self.presetExe)
        mainwindow.setTabOrder(self.presetExe, self.Settings)
        mainwindow.setTabOrder(self.Settings, self.freeButton)
        mainwindow.setTabOrder(self.freeButton, self.executeScript_button)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "MkECTL"))
        self.robotControl.setTitle(_translate("mainwindow", "Robot Control"))
        self.initializeProgressLabel.setText(_translate("mainwindow", "Initializing motors..."))
        self.Settings.setTitle(_translate("mainwindow", "Settings"))
        self.sliderSpeedLabel.setText(_translate("mainwindow", "Slider"))
        self.panSpeedLabel.setText(_translate("mainwindow", "Pan"))
        self.tiltSpeedLabel.setText(_translate("mainwindow", "Tilt"))
        self.radpersec.setText(_translate("mainwindow", "rad/s"))
        self.radpersec_2.setText(_translate("mainwindow", "rad/s"))
        self.radpersec_3.setText(_translate("mainwindow", "rad/s"))
        self.setSpeedLabel.setText(_translate("mainwindow", "Set speed"))
        self.presetLabel.setText(_translate("mainwindow", "Preset"))
        self.originLabel.setText(_translate("mainwindow", "Origin"))
        self.presetMotorCombo.setItemText(0, _translate("mainwindow", "slider"))
        self.presetMotorCombo.setItemText(1, _translate("mainwindow", "pan"))
        self.presetMotorCombo.setItemText(2, _translate("mainwindow", "tilt"))
        self.unitLabel.setText(_translate("mainwindow", "mm"))
        self.currentPoslabel.setText(_translate("mainwindow", "Current Pos."))
        self.currentSliderLabel.setText(_translate("mainwindow", "slider"))
        self.sliderCurrentPos.setText(_translate("mainwindow", "0"))
        self.currentPanLabel.setText(_translate("mainwindow", "pan"))
        self.panCurrentPos.setText(_translate("mainwindow", "0"))
        self.currentTiltLabel.setText(_translate("mainwindow", "tilt"))
        self.tiltCurrentPos.setText(_translate("mainwindow", "0"))
        self.motorConfigration.setTitle(_translate("mainwindow", "Motor Configuration"))
        self.saveButton.setText(_translate("mainwindow", "Save"))
        self.sliderOriginButton.setText(_translate("mainwindow", "Set Slider Origin"))
        self.freeButton.setText(_translate("mainwindow", "FREE all motors"))
        self.rebootButton.setText(_translate("mainwindow", "REBOOT all motors"))
        self.panLabel.setText(_translate("mainwindow", "Pan [-180 to 180 deg]"))
        self.sliderLabel.setText(_translate("mainwindow", "Slider [-4000 to 4000 mm]"))
        self.tiltLabel.setText(_translate("mainwindow", "Tilt [-180 to 180 deg]"))
        self.savedPositionslabel.setText(_translate("mainwindow", "Saved Positions [slider pan tilt]"))
        self.initializeButton.setText(_translate("mainwindow", "Initialize"))
        self.MagikEye.setText(_translate("mainwindow", "●MagikEye●"))
        self.Script_groupBox.setTitle(_translate("mainwindow", "Scripting"))
        self.showScriptName_label.setText(_translate("mainwindow", "Script name:"))
        self.selectScript_toolButton.setText(_translate("mainwindow", "..."))
        self.continueButton.setText(_translate("mainwindow", "Continue"))
        self.opsToExeScript_label.setText(_translate("mainwindow", "Ops to execute:"))
        self.viewSensorWinButton.setText(_translate("mainwindow", "Sensor Window"))
        self.laserControlGroup_2.setTitle(_translate("mainwindow", "IR Light Control"))
        self.L1Label.setText(_translate("mainwindow", "L1"))
        self.L2Label.setText(_translate("mainwindow", "L2"))
        self.IRstateLabel.setText(_translate("mainwindow", "Not connected"))
from MyDoubleSpinBox import MyDoubleSpinBox
import resources_rc
