# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/magikeye/bin/keiganGUI/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_keigan(object):
    def setupUi(self, keigan):
        keigan.setObjectName("keigan")
        keigan.resize(713, 628)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        keigan.setFont(font)
        self.centralwidget = QtWidgets.QWidget(keigan)
        self.centralwidget.setObjectName("centralwidget")
        self.robotControl = QtWidgets.QGroupBox(self.centralwidget)
        self.robotControl.setEnabled(True)
        self.robotControl.setGeometry(QtCore.QRect(20, 40, 631, 331))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.robotControl.sizePolicy().hasHeightForWidth())
        self.robotControl.setSizePolicy(sizePolicy)
        self.robotControl.setObjectName("robotControl")
        self.layoutWidget = QtWidgets.QWidget(self.robotControl)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 291, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.robotControlLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.robotControlLayout.setContentsMargins(0, 0, 0, 0)
        self.robotControlLayout.setObjectName("robotControlLayout")
        self.panLabel = QtWidgets.QLabel(self.layoutWidget)
        self.panLabel.setObjectName("panLabel")
        self.robotControlLayout.addWidget(self.panLabel, 1, 0, 1, 1)
        self.tiltMoveExe = QtWidgets.QPushButton(self.layoutWidget)
        self.tiltMoveExe.setMaximumSize(QtCore.QSize(24, 16777215))
        self.tiltMoveExe.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/magikeye/bin/keiganGUI/GUI_icons/exec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tiltMoveExe.setIcon(icon)
        self.tiltMoveExe.setAutoDefault(True)
        self.tiltMoveExe.setObjectName("tiltMoveExe")
        self.robotControlLayout.addWidget(self.tiltMoveExe, 2, 2, 1, 1)
        self.tiltPosSpin = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.tiltPosSpin.setDecimals(2)
        self.tiltPosSpin.setMinimum(-180.0)
        self.tiltPosSpin.setMaximum(180.0)
        self.tiltPosSpin.setSingleStep(0.1)
        self.tiltPosSpin.setObjectName("tiltPosSpin")
        self.robotControlLayout.addWidget(self.tiltPosSpin, 2, 1, 1, 1)
        self.sliderLabel = QtWidgets.QLabel(self.layoutWidget)
        self.sliderLabel.setObjectName("sliderLabel")
        self.robotControlLayout.addWidget(self.sliderLabel, 0, 0, 1, 1)
        self.panMoveExe = QtWidgets.QPushButton(self.layoutWidget)
        self.panMoveExe.setMaximumSize(QtCore.QSize(24, 16777215))
        self.panMoveExe.setText("")
        self.panMoveExe.setIcon(icon)
        self.panMoveExe.setAutoDefault(True)
        self.panMoveExe.setObjectName("panMoveExe")
        self.robotControlLayout.addWidget(self.panMoveExe, 1, 2, 1, 1)
        self.sliderMoveExe = QtWidgets.QPushButton(self.layoutWidget)
        self.sliderMoveExe.setMaximumSize(QtCore.QSize(24, 16777215))
        self.sliderMoveExe.setText("")
        self.sliderMoveExe.setIcon(icon)
        self.sliderMoveExe.setAutoDefault(True)
        self.sliderMoveExe.setObjectName("sliderMoveExe")
        self.robotControlLayout.addWidget(self.sliderMoveExe, 0, 2, 1, 1)
        self.panPosSpin = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.panPosSpin.setDecimals(2)
        self.panPosSpin.setMinimum(-180.0)
        self.panPosSpin.setMaximum(180.0)
        self.panPosSpin.setSingleStep(0.1)
        self.panPosSpin.setObjectName("panPosSpin")
        self.robotControlLayout.addWidget(self.panPosSpin, 1, 1, 1, 1)
        self.tiltLabel = QtWidgets.QLabel(self.layoutWidget)
        self.tiltLabel.setObjectName("tiltLabel")
        self.robotControlLayout.addWidget(self.tiltLabel, 2, 0, 1, 1)
        self.sliderPosSpin = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.sliderPosSpin.setDecimals(1)
        self.sliderPosSpin.setMinimum(-1000.0)
        self.sliderPosSpin.setMaximum(2100.0)
        self.sliderPosSpin.setSingleStep(5.0)
        self.sliderPosSpin.setObjectName("sliderPosSpin")
        self.robotControlLayout.addWidget(self.sliderPosSpin, 0, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.robotControl)
        self.layoutWidget1.setGeometry(QtCore.QRect(320, 30, 141, 120))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.initializeButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.initializeButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.initializeButton.setAutoDefault(True)
        self.initializeButton.setObjectName("initializeButton")
        self.verticalLayout.addWidget(self.initializeButton)
        self.sliderOriginButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.sliderOriginButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.sliderOriginButton.setAutoDefault(True)
        self.sliderOriginButton.setObjectName("sliderOriginButton")
        self.verticalLayout.addWidget(self.sliderOriginButton)
        self.freeButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.freeButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.freeButton.setAutoDefault(True)
        self.freeButton.setObjectName("freeButton")
        self.verticalLayout.addWidget(self.freeButton)
        self.rebootButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.rebootButton.setMinimumSize(QtCore.QSize(50, 0))
        self.rebootButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.rebootButton.setAutoDefault(True)
        self.rebootButton.setDefault(False)
        self.rebootButton.setFlat(False)
        self.rebootButton.setObjectName("rebootButton")
        self.verticalLayout.addWidget(self.rebootButton)
        self.initializeProgressLabel = QtWidgets.QLabel(self.robotControl)
        self.initializeProgressLabel.setEnabled(False)
        self.initializeProgressLabel.setGeometry(QtCore.QRect(480, 30, 141, 17))
        self.initializeProgressLabel.setObjectName("initializeProgressLabel")
        self.initializeProgressBar = QtWidgets.QProgressBar(self.robotControl)
        self.initializeProgressBar.setEnabled(False)
        self.initializeProgressBar.setGeometry(QtCore.QRect(480, 50, 118, 23))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(False)
        font.setWeight(50)
        self.initializeProgressBar.setFont(font)
        self.initializeProgressBar.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.initializeProgressBar.setProperty("value", 0)
        self.initializeProgressBar.setObjectName("initializeProgressBar")
        self.Settings = QtWidgets.QGroupBox(self.robotControl)
        self.Settings.setEnabled(True)
        self.Settings.setGeometry(QtCore.QRect(20, 160, 461, 161))
        self.Settings.setAutoFillBackground(False)
        self.Settings.setFlat(False)
        self.Settings.setCheckable(True)
        self.Settings.setChecked(True)
        self.Settings.setObjectName("Settings")
        self.layoutWidget2 = QtWidgets.QWidget(self.Settings)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 50, 181, 94))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sliderSpeedLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.sliderSpeedLabel.setObjectName("sliderSpeedLabel")
        self.verticalLayout_2.addWidget(self.sliderSpeedLabel)
        self.panSpeedLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.panSpeedLabel.setObjectName("panSpeedLabel")
        self.verticalLayout_2.addWidget(self.panSpeedLabel)
        self.tiltSpeedLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.tiltSpeedLabel.setObjectName("tiltSpeedLabel")
        self.verticalLayout_2.addWidget(self.tiltSpeedLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sliderSpeedSpin = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.sliderSpeedSpin.setDecimals(1)
        self.sliderSpeedSpin.setProperty("value", 20.0)
        self.sliderSpeedSpin.setObjectName("sliderSpeedSpin")
        self.verticalLayout_3.addWidget(self.sliderSpeedSpin)
        self.panSpeedSpin = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.panSpeedSpin.setDecimals(1)
        self.panSpeedSpin.setProperty("value", 5.0)
        self.panSpeedSpin.setObjectName("panSpeedSpin")
        self.verticalLayout_3.addWidget(self.panSpeedSpin)
        self.tiltSpeedSpin = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.tiltSpeedSpin.setDecimals(1)
        self.tiltSpeedSpin.setProperty("value", 5.0)
        self.tiltSpeedSpin.setObjectName("tiltSpeedSpin")
        self.verticalLayout_3.addWidget(self.tiltSpeedSpin)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radpersec = QtWidgets.QLabel(self.layoutWidget2)
        self.radpersec.setMinimumSize(QtCore.QSize(40, 0))
        self.radpersec.setObjectName("radpersec")
        self.verticalLayout_4.addWidget(self.radpersec)
        self.radpersec_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.radpersec_2.setMinimumSize(QtCore.QSize(40, 0))
        self.radpersec_2.setObjectName("radpersec_2")
        self.verticalLayout_4.addWidget(self.radpersec_2)
        self.radpersec_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.radpersec_3.setMinimumSize(QtCore.QSize(40, 0))
        self.radpersec_3.setObjectName("radpersec_3")
        self.verticalLayout_4.addWidget(self.radpersec_3)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.setSpeedLabel = QtWidgets.QLabel(self.Settings)
        self.setSpeedLabel.setGeometry(QtCore.QRect(20, 30, 100, 16))
        self.setSpeedLabel.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.setSpeedLabel.setFont(font)
        self.setSpeedLabel.setObjectName("setSpeedLabel")
        self.presetLabel = QtWidgets.QLabel(self.Settings)
        self.presetLabel.setGeometry(QtCore.QRect(240, 30, 69, 20))
        self.presetLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.presetLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.presetLabel.setFont(font)
        self.presetLabel.setObjectName("presetLabel")
        self.layoutWidget3 = QtWidgets.QWidget(self.Settings)
        self.layoutWidget3.setGeometry(QtCore.QRect(240, 110, 68, 27))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.homeGridLayout = QtWidgets.QGridLayout(self.layoutWidget3)
        self.homeGridLayout.setContentsMargins(0, 0, 0, 0)
        self.homeGridLayout.setObjectName("homeGridLayout")
        self.setAsHomeButton = QtWidgets.QPushButton(self.layoutWidget3)
        self.setAsHomeButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.setAsHomeButton.setObjectName("setAsHomeButton")
        self.homeGridLayout.addWidget(self.setAsHomeButton, 0, 0, 1, 1)
        self.goHomeButton = QtWidgets.QPushButton(self.layoutWidget3)
        self.goHomeButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.goHomeButton.setObjectName("goHomeButton")
        self.homeGridLayout.addWidget(self.goHomeButton, 0, 1, 1, 1)
        self.originLabel = QtWidgets.QLabel(self.Settings)
        self.originLabel.setGeometry(QtCore.QRect(240, 90, 69, 20))
        self.originLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.originLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.originLabel.setFont(font)
        self.originLabel.setObjectName("originLabel")
        self.widget = QtWidgets.QWidget(self.Settings)
        self.widget.setGeometry(QtCore.QRect(240, 50, 211, 29))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.presetMotorCombo = QtWidgets.QComboBox(self.widget)
        self.presetMotorCombo.setMaximumSize(QtCore.QSize(70, 16777215))
        self.presetMotorCombo.setObjectName("presetMotorCombo")
        self.presetMotorCombo.addItem("")
        self.presetMotorCombo.addItem("")
        self.presetMotorCombo.addItem("")
        self.horizontalLayout_4.addWidget(self.presetMotorCombo)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.presetValue = QtWidgets.QLineEdit(self.widget)
        self.presetValue.setMinimumSize(QtCore.QSize(0, 0))
        self.presetValue.setObjectName("presetValue")
        self.horizontalLayout_3.addWidget(self.presetValue)
        self.unitLabel = QtWidgets.QLabel(self.widget)
        self.unitLabel.setMinimumSize(QtCore.QSize(30, 0))
        self.unitLabel.setObjectName("unitLabel")
        self.horizontalLayout_3.addWidget(self.unitLabel)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.presetExe = QtWidgets.QPushButton(self.widget)
        self.presetExe.setMaximumSize(QtCore.QSize(24, 16777215))
        self.presetExe.setText("")
        self.presetExe.setIcon(icon)
        self.presetExe.setAutoDefault(True)
        self.presetExe.setObjectName("presetExe")
        self.horizontalLayout_4.addWidget(self.presetExe)
        self.MagikEye = QtWidgets.QPushButton(self.centralwidget)
        self.MagikEye.setGeometry(QtCore.QRect(510, 20, 101, 25))
        self.MagikEye.setAutoDefault(True)
        self.MagikEye.setObjectName("MagikEye")
        self.Script_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.Script_groupBox.setGeometry(QtCore.QRect(20, 460, 331, 111))
        self.Script_groupBox.setObjectName("Script_groupBox")
        self.showScriptName_label = QtWidgets.QLabel(self.Script_groupBox)
        self.showScriptName_label.setGeometry(QtCore.QRect(10, 30, 91, 17))
        self.showScriptName_label.setObjectName("showScriptName_label")
        self.executeScript_button = QtWidgets.QPushButton(self.Script_groupBox)
        self.executeScript_button.setGeometry(QtCore.QRect(210, 80, 24, 24))
        self.executeScript_button.setText("")
        self.executeScript_button.setIcon(icon)
        self.executeScript_button.setObjectName("executeScript_button")
        self.layoutWidget4 = QtWidgets.QWidget(self.Script_groupBox)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 50, 311, 26))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scriptName_label = QtWidgets.QLabel(self.layoutWidget4)
        self.scriptName_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scriptName_label.setText("")
        self.scriptName_label.setObjectName("scriptName_label")
        self.horizontalLayout_2.addWidget(self.scriptName_label)
        self.selectScript_toolButton = QtWidgets.QToolButton(self.layoutWidget4)
        self.selectScript_toolButton.setObjectName("selectScript_toolButton")
        self.horizontalLayout_2.addWidget(self.selectScript_toolButton)
        self.continueButton = QtWidgets.QPushButton(self.Script_groupBox)
        self.continueButton.setGeometry(QtCore.QRect(128, 80, 71, 24))
        self.continueButton.setObjectName("continueButton")
        self.opsToExeScript_label = QtWidgets.QLabel(self.Script_groupBox)
        self.opsToExeScript_label.setGeometry(QtCore.QRect(10, 80, 121, 17))
        self.opsToExeScript_label.setObjectName("opsToExeScript_label")
        self.dummyMode = QtWidgets.QGroupBox(self.centralwidget)
        self.dummyMode.setEnabled(True)
        self.dummyMode.setGeometry(QtCore.QRect(370, 440, 281, 131))
        self.dummyMode.setCheckable(True)
        self.dummyMode.setChecked(True)
        self.dummyMode.setObjectName("dummyMode")
        self.layoutWidget5 = QtWidgets.QWidget(self.dummyMode)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 30, 261, 91))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.currentPosLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.currentPosLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.currentPosLabel.setObjectName("currentPosLabel")
        self.gridLayout.addWidget(self.currentPosLabel, 0, 1, 1, 1)
        self.nextPosLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.nextPosLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nextPosLabel.setObjectName("nextPosLabel")
        self.gridLayout.addWidget(self.nextPosLabel, 0, 2, 1, 1)
        self.sliderDummyLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.sliderDummyLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.sliderDummyLabel.setMaximumSize(QtCore.QSize(50, 15))
        self.sliderDummyLabel.setObjectName("sliderDummyLabel")
        self.gridLayout.addWidget(self.sliderDummyLabel, 1, 0, 1, 1)
        self.sliderCurrentLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.sliderCurrentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sliderCurrentLabel.setObjectName("sliderCurrentLabel")
        self.gridLayout.addWidget(self.sliderCurrentLabel, 1, 1, 1, 1)
        self.sliderNextLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.sliderNextLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sliderNextLabel.setObjectName("sliderNextLabel")
        self.gridLayout.addWidget(self.sliderNextLabel, 1, 2, 1, 1)
        self.panDummyLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.panDummyLabel.setObjectName("panDummyLabel")
        self.gridLayout.addWidget(self.panDummyLabel, 2, 0, 1, 1)
        self.panCurrentLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.panCurrentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.panCurrentLabel.setObjectName("panCurrentLabel")
        self.gridLayout.addWidget(self.panCurrentLabel, 2, 1, 1, 1)
        self.panNextLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.panNextLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.panNextLabel.setObjectName("panNextLabel")
        self.gridLayout.addWidget(self.panNextLabel, 2, 2, 1, 1)
        self.tiltDummyLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.tiltDummyLabel.setObjectName("tiltDummyLabel")
        self.gridLayout.addWidget(self.tiltDummyLabel, 3, 0, 1, 1)
        self.tiltCurrentLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.tiltCurrentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tiltCurrentLabel.setObjectName("tiltCurrentLabel")
        self.gridLayout.addWidget(self.tiltCurrentLabel, 3, 1, 1, 1)
        self.tiltNextLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.tiltNextLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tiltNextLabel.setObjectName("tiltNextLabel")
        self.gridLayout.addWidget(self.tiltNextLabel, 3, 2, 1, 1)
        self.viewSensorWinButton = QtWidgets.QPushButton(self.centralwidget)
        self.viewSensorWinButton.setGeometry(QtCore.QRect(380, 20, 121, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 201, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 117, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 215, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 201, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 117, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 215, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 201, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 117, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.viewSensorWinButton.setPalette(palette)
        self.viewSensorWinButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.viewSensorWinButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.viewSensorWinButton.setObjectName("viewSensorWinButton")
        self.laserControlGroup_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.laserControlGroup_2.setGeometry(QtCore.QRect(20, 380, 231, 71))
        self.laserControlGroup_2.setObjectName("laserControlGroup_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.laserControlGroup_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 30, 101, 31))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.L1GridLayout = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.L1GridLayout.setContentsMargins(0, 0, 0, 0)
        self.L1GridLayout.setObjectName("L1GridLayout")
        self.L1Label = QtWidgets.QLabel(self.layoutWidget_2)
        self.L1Label.setMaximumSize(QtCore.QSize(20, 16777215))
        self.L1Label.setObjectName("L1Label")
        self.L1GridLayout.addWidget(self.L1Label, 0, 0, 1, 1)
        self.onL1Button = QtWidgets.QPushButton(self.layoutWidget_2)
        self.onL1Button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.onL1Button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/home/magikeye/bin/keiganGUI/GUI_icons/lightON.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.onL1Button.setIcon(icon1)
        self.onL1Button.setObjectName("onL1Button")
        self.L1GridLayout.addWidget(self.onL1Button, 0, 1, 1, 1)
        self.offL1Button = QtWidgets.QPushButton(self.layoutWidget_2)
        self.offL1Button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.offL1Button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/home/magikeye/bin/keiganGUI/GUI_icons/lightOFF.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.offL1Button.setIcon(icon2)
        self.offL1Button.setObjectName("offL1Button")
        self.L1GridLayout.addWidget(self.offL1Button, 0, 2, 1, 1)
        self.layoutWidget_4 = QtWidgets.QWidget(self.laserControlGroup_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(120, 30, 101, 31))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.L2GridLayout = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.L2GridLayout.setContentsMargins(0, 0, 0, 0)
        self.L2GridLayout.setObjectName("L2GridLayout")
        self.L2Label = QtWidgets.QLabel(self.layoutWidget_4)
        self.L2Label.setMaximumSize(QtCore.QSize(20, 16777215))
        self.L2Label.setObjectName("L2Label")
        self.L2GridLayout.addWidget(self.L2Label, 0, 0, 1, 1)
        self.onL2Button = QtWidgets.QPushButton(self.layoutWidget_4)
        self.onL2Button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.onL2Button.setText("")
        self.onL2Button.setIcon(icon1)
        self.onL2Button.setObjectName("onL2Button")
        self.L2GridLayout.addWidget(self.onL2Button, 0, 1, 1, 1)
        self.offL2Button = QtWidgets.QPushButton(self.layoutWidget_4)
        self.offL2Button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.offL2Button.setText("")
        self.offL2Button.setIcon(icon2)
        self.offL2Button.setObjectName("offL2Button")
        self.L2GridLayout.addWidget(self.offL2Button, 0, 2, 1, 1)
        keigan.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(keigan)
        self.statusbar.setObjectName("statusbar")
        keigan.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(keigan)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 22))
        self.menubar.setObjectName("menubar")
        keigan.setMenuBar(self.menubar)

        self.retranslateUi(keigan)
        QtCore.QMetaObject.connectSlotsByName(keigan)
        keigan.setTabOrder(self.initializeButton, self.sliderOriginButton)
        keigan.setTabOrder(self.sliderOriginButton, self.MagikEye)
        keigan.setTabOrder(self.MagikEye, self.sliderPosSpin)
        keigan.setTabOrder(self.sliderPosSpin, self.panPosSpin)
        keigan.setTabOrder(self.panPosSpin, self.tiltPosSpin)
        keigan.setTabOrder(self.tiltPosSpin, self.sliderMoveExe)
        keigan.setTabOrder(self.sliderMoveExe, self.panMoveExe)
        keigan.setTabOrder(self.panMoveExe, self.tiltMoveExe)
        keigan.setTabOrder(self.tiltMoveExe, self.sliderSpeedSpin)
        keigan.setTabOrder(self.sliderSpeedSpin, self.panSpeedSpin)
        keigan.setTabOrder(self.panSpeedSpin, self.tiltSpeedSpin)
        keigan.setTabOrder(self.tiltSpeedSpin, self.presetMotorCombo)
        keigan.setTabOrder(self.presetMotorCombo, self.presetValue)
        keigan.setTabOrder(self.presetValue, self.presetExe)
        keigan.setTabOrder(self.presetExe, self.Settings)
        keigan.setTabOrder(self.Settings, self.freeButton)
        keigan.setTabOrder(self.freeButton, self.executeScript_button)

    def retranslateUi(self, keigan):
        _translate = QtCore.QCoreApplication.translate
        keigan.setWindowTitle(_translate("keigan", "keiganGUI"))
        self.robotControl.setTitle(_translate("keigan", "Robot Control"))
        self.panLabel.setText(_translate("keigan", "Pan [-90 to 90 deg]"))
        self.sliderLabel.setText(_translate("keigan", "Slider [-1000 to 2100 mm]"))
        self.tiltLabel.setText(_translate("keigan", "Tilt [-90 to 90 deg]"))
        self.initializeButton.setText(_translate("keigan", "Initialize"))
        self.sliderOriginButton.setText(_translate("keigan", "Set Slider Origin"))
        self.freeButton.setText(_translate("keigan", "FREE all motors"))
        self.rebootButton.setText(_translate("keigan", "REBOOT all motors"))
        self.initializeProgressLabel.setText(_translate("keigan", "Initializing motors..."))
        self.Settings.setTitle(_translate("keigan", "Settings"))
        self.sliderSpeedLabel.setText(_translate("keigan", "Slider"))
        self.panSpeedLabel.setText(_translate("keigan", "Pan"))
        self.tiltSpeedLabel.setText(_translate("keigan", "Tilt"))
        self.radpersec.setText(_translate("keigan", "rad/s"))
        self.radpersec_2.setText(_translate("keigan", "rad/s"))
        self.radpersec_3.setText(_translate("keigan", "rad/s"))
        self.setSpeedLabel.setText(_translate("keigan", "Set speed"))
        self.presetLabel.setText(_translate("keigan", "Preset"))
        self.setAsHomeButton.setText(_translate("keigan", "Set"))
        self.goHomeButton.setText(_translate("keigan", "Go"))
        self.originLabel.setText(_translate("keigan", "Origin"))
        self.presetMotorCombo.setItemText(0, _translate("keigan", "Slider"))
        self.presetMotorCombo.setItemText(1, _translate("keigan", "Pan"))
        self.presetMotorCombo.setItemText(2, _translate("keigan", "Tilt"))
        self.unitLabel.setText(_translate("keigan", "mm"))
        self.MagikEye.setText(_translate("keigan", "●MagikEye●"))
        self.Script_groupBox.setTitle(_translate("keigan", "Scripting"))
        self.showScriptName_label.setText(_translate("keigan", "Script name:"))
        self.selectScript_toolButton.setText(_translate("keigan", "..."))
        self.continueButton.setText(_translate("keigan", "Continue"))
        self.opsToExeScript_label.setText(_translate("keigan", "Ops to execute:"))
        self.dummyMode.setTitle(_translate("keigan", "Dummy mode"))
        self.currentPosLabel.setText(_translate("keigan", "current pos."))
        self.nextPosLabel.setText(_translate("keigan", "next pos."))
        self.sliderDummyLabel.setText(_translate("keigan", "Slider"))
        self.sliderCurrentLabel.setText(_translate("keigan", "0"))
        self.sliderNextLabel.setText(_translate("keigan", "0"))
        self.panDummyLabel.setText(_translate("keigan", "Pan"))
        self.panCurrentLabel.setText(_translate("keigan", "0"))
        self.panNextLabel.setText(_translate("keigan", "0"))
        self.tiltDummyLabel.setText(_translate("keigan", "Tilt"))
        self.tiltCurrentLabel.setText(_translate("keigan", "0"))
        self.tiltNextLabel.setText(_translate("keigan", "0"))
        self.viewSensorWinButton.setText(_translate("keigan", "Sensor Window"))
        self.laserControlGroup_2.setTitle(_translate("keigan", "IR Light Control"))
        self.L1Label.setText(_translate("keigan", "L1"))
        self.L2Label.setText(_translate("keigan", "L2"))
