# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/magikeye/bin/keiganGUI/sensorwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sensor(object):
    def setupUi(self, sensor):
        sensor.setObjectName("sensor")
        sensor.resize(932, 537)
        self.sensorImage = QtWidgets.QGraphicsView(sensor)
        self.sensorImage.setGeometry(QtCore.QRect(20, 10, 640, 480))
        self.sensorImage.setObjectName("sensorImage")
        self.cameraControlGroup = QtWidgets.QGroupBox(sensor)
        self.cameraControlGroup.setGeometry(QtCore.QRect(680, 40, 231, 201))
        self.cameraControlGroup.setObjectName("cameraControlGroup")
        self.previewGroup = QtWidgets.QGroupBox(self.cameraControlGroup)
        self.previewGroup.setGeometry(QtCore.QRect(10, 119, 101, 71))
        self.previewGroup.setObjectName("previewGroup")
        self.prev1Button = QtWidgets.QPushButton(self.previewGroup)
        self.prev1Button.setGeometry(QtCore.QRect(10, 30, 31, 31))
        self.prev1Button.setObjectName("prev1Button")
        self.prevAveButton = QtWidgets.QPushButton(self.previewGroup)
        self.prevAveButton.setGeometry(QtCore.QRect(60, 30, 31, 31))
        self.prevAveButton.setObjectName("prevAveButton")
        self.preview_save_Group = QtWidgets.QGroupBox(self.cameraControlGroup)
        self.preview_save_Group.setGeometry(QtCore.QRect(120, 120, 101, 71))
        self.preview_save_Group.setObjectName("preview_save_Group")
        self.saveAveButton = QtWidgets.QPushButton(self.preview_save_Group)
        self.saveAveButton.setGeometry(QtCore.QRect(60, 30, 31, 31))
        self.saveAveButton.setObjectName("saveAveButton")
        self.save1Button = QtWidgets.QPushButton(self.preview_save_Group)
        self.save1Button.setGeometry(QtCore.QRect(10, 30, 31, 31))
        self.save1Button.setObjectName("save1Button")
        self.layoutWidget = QtWidgets.QWidget(self.cameraControlGroup)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 211, 89))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.shutterLabel = QtWidgets.QLabel(self.layoutWidget)
        self.shutterLabel.setObjectName("shutterLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.shutterLabel)
        self.shutterLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.shutterLineEdit.setObjectName("shutterLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.shutterLineEdit)
        self.framesLabel = QtWidgets.QLabel(self.layoutWidget)
        self.framesLabel.setObjectName("framesLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.framesLabel)
        self.framesLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.framesLineEdit.setObjectName("framesLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.framesLineEdit)
        self.ISOlabel = QtWidgets.QLabel(self.layoutWidget)
        self.ISOlabel.setObjectName("ISOlabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.ISOlabel)
        self.ISOcombo = QtWidgets.QComboBox(self.layoutWidget)
        self.ISOcombo.setObjectName("ISOcombo")
        self.ISOcombo.addItem("")
        self.ISOcombo.addItem("")
        self.ISOcombo.addItem("")
        self.ISOcombo.addItem("")
        self.ISOcombo.addItem("")
        self.ISOcombo.addItem("")
        self.ISOcombo.addItem("")
        self.ISOcombo.addItem("")
        self.ISOcombo.addItem("")
        self.ISOcombo.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ISOcombo)
        self.laserControlGroup = QtWidgets.QGroupBox(sensor)
        self.laserControlGroup.setGeometry(QtCore.QRect(680, 250, 231, 61))
        self.laserControlGroup.setObjectName("laserControlGroup")
        self.evenLaserButton = QtWidgets.QPushButton(self.laserControlGroup)
        self.evenLaserButton.setGeometry(QtCore.QRect(20, 30, 41, 25))
        self.evenLaserButton.setObjectName("evenLaserButton")
        self.oddLaserButton = QtWidgets.QPushButton(self.laserControlGroup)
        self.oddLaserButton.setGeometry(QtCore.QRect(70, 30, 41, 25))
        self.oddLaserButton.setObjectName("oddLaserButton")
        self.onAllLaserButton = QtWidgets.QPushButton(self.laserControlGroup)
        self.onAllLaserButton.setGeometry(QtCore.QRect(120, 30, 41, 25))
        self.onAllLaserButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/magikeye/bin/keiganGUI/GUI_icons/lightON.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.onAllLaserButton.setIcon(icon)
        self.onAllLaserButton.setObjectName("onAllLaserButton")
        self.offAllLaserButton = QtWidgets.QPushButton(self.laserControlGroup)
        self.offAllLaserButton.setGeometry(QtCore.QRect(170, 30, 41, 25))
        self.offAllLaserButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/home/magikeye/bin/keiganGUI/GUI_icons/lightOFF.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.offAllLaserButton.setIcon(icon1)
        self.offAllLaserButton.setObjectName("offAllLaserButton")
        self.layoutWidget1 = QtWidgets.QWidget(sensor)
        self.layoutWidget1.setGeometry(QtCore.QRect(680, 10, 231, 27))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.IPlabel = QtWidgets.QLabel(self.layoutWidget1)
        self.IPlabel.setObjectName("IPlabel")
        self.horizontalLayout.addWidget(self.IPlabel)
        self.IPlineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.IPlineEdit.setObjectName("IPlineEdit")
        self.horizontalLayout.addWidget(self.IPlineEdit)
        self.cameraStatusLabel = QtWidgets.QLabel(sensor)
        self.cameraStatusLabel.setGeometry(QtCore.QRect(20, 500, 321, 17))
        self.cameraStatusLabel.setObjectName("cameraStatusLabel")

        self.retranslateUi(sensor)
        QtCore.QMetaObject.connectSlotsByName(sensor)

    def retranslateUi(self, sensor):
        _translate = QtCore.QCoreApplication.translate
        sensor.setWindowTitle(_translate("sensor", "Sensor Window"))
        self.cameraControlGroup.setTitle(_translate("sensor", "Camera Control"))
        self.previewGroup.setTitle(_translate("sensor", "Preview"))
        self.prev1Button.setText(_translate("sensor", "1"))
        self.prevAveButton.setText(_translate("sensor", "#"))
        self.preview_save_Group.setTitle(_translate("sensor", "Preview\'n\'Save"))
        self.saveAveButton.setText(_translate("sensor", "#"))
        self.save1Button.setText(_translate("sensor", "1"))
        self.shutterLabel.setText(_translate("sensor", "Shutter [us]"))
        self.framesLabel.setText(_translate("sensor", "#~frames"))
        self.ISOlabel.setText(_translate("sensor", "ISO"))
        self.ISOcombo.setItemText(0, _translate("sensor", "100"))
        self.ISOcombo.setItemText(1, _translate("sensor", "200"))
        self.ISOcombo.setItemText(2, _translate("sensor", "500"))
        self.ISOcombo.setItemText(3, _translate("sensor", "1000"))
        self.ISOcombo.setItemText(4, _translate("sensor", "5000"))
        self.ISOcombo.setItemText(5, _translate("sensor", "10000"))
        self.ISOcombo.setItemText(6, _translate("sensor", "20000"))
        self.ISOcombo.setItemText(7, _translate("sensor", "50000"))
        self.ISOcombo.setItemText(8, _translate("sensor", "80000"))
        self.ISOcombo.setItemText(9, _translate("sensor", "100000"))
        self.laserControlGroup.setTitle(_translate("sensor", "Laser Control"))
        self.evenLaserButton.setText(_translate("sensor", "EVEN"))
        self.oddLaserButton.setText(_translate("sensor", "ODD"))
        self.IPlabel.setText(_translate("sensor", "RPi adress"))
        self.cameraStatusLabel.setText(_translate("sensor", "!!No cameras were detected."))
