# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/magikeye/bin/keiganGUI/sensorwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sensor(object):
    def setupUi(self, sensor):
        sensor.setObjectName("sensor")
        sensor.resize(932, 537)
        self.sensorImage = QtWidgets.QGraphicsView(sensor)
        self.sensorImage.setGeometry(QtCore.QRect(20, 10, 640, 480))
        self.sensorImage.setObjectName("sensorImage")
        self.cameraControlGroup = QtWidgets.QGroupBox(sensor)
        self.cameraControlGroup.setGeometry(QtCore.QRect(680, 70, 231, 251))
        self.cameraControlGroup.setObjectName("cameraControlGroup")
        self.previewGroup = QtWidgets.QGroupBox(self.cameraControlGroup)
        self.previewGroup.setGeometry(QtCore.QRect(10, 169, 101, 71))
        self.previewGroup.setObjectName("previewGroup")
        self.prev1Button = QtWidgets.QPushButton(self.previewGroup)
        self.prev1Button.setGeometry(QtCore.QRect(10, 30, 31, 31))
        self.prev1Button.setObjectName("prev1Button")
        self.prevAveButton = QtWidgets.QPushButton(self.previewGroup)
        self.prevAveButton.setGeometry(QtCore.QRect(60, 30, 31, 31))
        self.prevAveButton.setObjectName("prevAveButton")
        self.preview_save_Group = QtWidgets.QGroupBox(self.cameraControlGroup)
        self.preview_save_Group.setGeometry(QtCore.QRect(120, 170, 101, 71))
        self.preview_save_Group.setObjectName("preview_save_Group")
        self.saveAveButton = QtWidgets.QPushButton(self.preview_save_Group)
        self.saveAveButton.setGeometry(QtCore.QRect(60, 30, 31, 31))
        self.saveAveButton.setObjectName("saveAveButton")
        self.save1Button = QtWidgets.QPushButton(self.preview_save_Group)
        self.save1Button.setGeometry(QtCore.QRect(10, 30, 31, 31))
        self.save1Button.setObjectName("save1Button")
        self.layoutWidget = QtWidgets.QWidget(self.cameraControlGroup)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 211, 120))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.shutterLabel = QtWidgets.QLabel(self.layoutWidget)
        self.shutterLabel.setObjectName("shutterLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.shutterLabel)
        self.shutterLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.shutterLineEdit.setText("")
        self.shutterLineEdit.setObjectName("shutterLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.shutterLineEdit)
        self.framesLabel = QtWidgets.QLabel(self.layoutWidget)
        self.framesLabel.setObjectName("framesLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.framesLabel)
        self.framesLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.framesLineEdit.setText("")
        self.framesLineEdit.setObjectName("framesLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.framesLineEdit)
        self.ISOlabel = QtWidgets.QLabel(self.layoutWidget)
        self.ISOlabel.setObjectName("ISOlabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.ISOlabel)
        self.ISOcombo = QtWidgets.QComboBox(self.layoutWidget)
        self.ISOcombo.setObjectName("ISOcombo")
        self.ISOcombo.addItem("")
        self.ISOcombo.addItem("")
        self.ISOcombo.addItem("")
        self.ISOcombo.addItem("")
        self.ISOcombo.addItem("")
        self.ISOcombo.addItem("")
        self.ISOcombo.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ISOcombo)
        self.ISOlineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.ISOlineEdit.setEnabled(False)
        self.ISOlineEdit.setInputMask("")
        self.ISOlineEdit.setObjectName("ISOlineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ISOlineEdit)
        self.laserControlGroup = QtWidgets.QGroupBox(sensor)
        self.laserControlGroup.setGeometry(QtCore.QRect(680, 340, 231, 181))
        self.laserControlGroup.setObjectName("laserControlGroup")
        self.evenLaserButton = QtWidgets.QPushButton(self.laserControlGroup)
        self.evenLaserButton.setGeometry(QtCore.QRect(20, 30, 41, 25))
        self.evenLaserButton.setObjectName("evenLaserButton")
        self.oddLaserButton = QtWidgets.QPushButton(self.laserControlGroup)
        self.oddLaserButton.setGeometry(QtCore.QRect(70, 30, 41, 25))
        self.oddLaserButton.setObjectName("oddLaserButton")
        self.onAllLaserButton = QtWidgets.QPushButton(self.laserControlGroup)
        self.onAllLaserButton.setGeometry(QtCore.QRect(120, 30, 41, 25))
        self.onAllLaserButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/magikeye/bin/keiganGUI/GUI_icons/lightON.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.onAllLaserButton.setIcon(icon)
        self.onAllLaserButton.setObjectName("onAllLaserButton")
        self.offAllLaserButton = QtWidgets.QPushButton(self.laserControlGroup)
        self.offAllLaserButton.setGeometry(QtCore.QRect(170, 30, 41, 25))
        self.offAllLaserButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/home/magikeye/bin/keiganGUI/GUI_icons/lightOFF.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.offAllLaserButton.setIcon(icon1)
        self.offAllLaserButton.setObjectName("offAllLaserButton")
        self.hex4dLineEdit = QtWidgets.QLineEdit(self.laserControlGroup)
        self.hex4dLineEdit.setEnabled(False)
        self.hex4dLineEdit.setGeometry(QtCore.QRect(60, 100, 91, 25))
        self.hex4dLineEdit.setObjectName("hex4dLineEdit")
        self.hex4dCheckBox = QtWidgets.QCheckBox(self.laserControlGroup)
        self.hex4dCheckBox.setEnabled(True)
        self.hex4dCheckBox.setGeometry(QtCore.QRect(20, 70, 131, 23))
        self.hex4dCheckBox.setObjectName("hex4dCheckBox")
        self.setHex4dLaserButton = QtWidgets.QPushButton(self.laserControlGroup)
        self.setHex4dLaserButton.setEnabled(False)
        self.setHex4dLaserButton.setGeometry(QtCore.QRect(160, 100, 31, 25))
        self.setHex4dLaserButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/home/magikeye/bin/keiganGUI/GUI_icons/exec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setHex4dLaserButton.setIcon(icon2)
        self.setHex4dLaserButton.setObjectName("setHex4dLaserButton")
        self.CurrentLaserPattern_label = QtWidgets.QLabel(self.laserControlGroup)
        self.CurrentLaserPattern_label.setGeometry(QtCore.QRect(10, 130, 221, 17))
        self.CurrentLaserPattern_label.setObjectName("CurrentLaserPattern_label")
        self.CurrentLaserPattern_value = QtWidgets.QLabel(self.laserControlGroup)
        self.CurrentLaserPattern_value.setGeometry(QtCore.QRect(10, 150, 211, 20))
        self.CurrentLaserPattern_value.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CurrentLaserPattern_value.setText("")
        self.CurrentLaserPattern_value.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentLaserPattern_value.setObjectName("CurrentLaserPattern_value")
        self.cameraStatusLabel = QtWidgets.QLabel(sensor)
        self.cameraStatusLabel.setGeometry(QtCore.QRect(20, 500, 321, 17))
        self.cameraStatusLabel.setObjectName("cameraStatusLabel")
        self.reconnectButton = QtWidgets.QPushButton(sensor)
        self.reconnectButton.setGeometry(QtCore.QRect(570, 500, 89, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 201, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 117, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 215, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 201, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 117, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 215, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 201, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 117, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.reconnectButton.setPalette(palette)
        self.reconnectButton.setObjectName("reconnectButton")
        self.widget = QtWidgets.QWidget(sensor)
        self.widget.setGeometry(QtCore.QRect(680, 11, 231, 51))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.IPlabel = QtWidgets.QLabel(self.widget)
        self.IPlabel.setObjectName("IPlabel")
        self.gridLayout.addWidget(self.IPlabel, 0, 0, 1, 1)
        self.IPlineEdit = QtWidgets.QLineEdit(self.widget)
        self.IPlineEdit.setObjectName("IPlineEdit")
        self.gridLayout.addWidget(self.IPlineEdit, 1, 0, 1, 1)
        self.setIPaddressButton = QtWidgets.QPushButton(self.widget)
        self.setIPaddressButton.setEnabled(True)
        self.setIPaddressButton.setText("")
        self.setIPaddressButton.setIcon(icon2)
        self.setIPaddressButton.setObjectName("setIPaddressButton")
        self.gridLayout.addWidget(self.setIPaddressButton, 1, 1, 1, 1)

        self.retranslateUi(sensor)
        QtCore.QMetaObject.connectSlotsByName(sensor)

    def retranslateUi(self, sensor):
        _translate = QtCore.QCoreApplication.translate
        sensor.setWindowTitle(_translate("sensor", "Sensor Window"))
        self.cameraControlGroup.setTitle(_translate("sensor", "Camera Control"))
        self.previewGroup.setTitle(_translate("sensor", "Preview"))
        self.prev1Button.setText(_translate("sensor", "1"))
        self.prevAveButton.setText(_translate("sensor", "#"))
        self.preview_save_Group.setTitle(_translate("sensor", "Preview\'n\'Save"))
        self.saveAveButton.setText(_translate("sensor", "#"))
        self.save1Button.setText(_translate("sensor", "1"))
        self.shutterLabel.setText(_translate("sensor", "Shutter [us]"))
        self.framesLabel.setText(_translate("sensor", "#~frames"))
        self.ISOlabel.setText(_translate("sensor", "ISO"))
        self.ISOcombo.setItemText(0, _translate("sensor", "100"))
        self.ISOcombo.setItemText(1, _translate("sensor", "200"))
        self.ISOcombo.setItemText(2, _translate("sensor", "400"))
        self.ISOcombo.setItemText(3, _translate("sensor", "800"))
        self.ISOcombo.setItemText(4, _translate("sensor", "1600"))
        self.ISOcombo.setItemText(5, _translate("sensor", "3200"))
        self.ISOcombo.setItemText(6, _translate("sensor", "Custom"))
        self.ISOlineEdit.setToolTip(_translate("sensor", "<html><head/><body><p><br/></p></body></html>"))
        self.laserControlGroup.setTitle(_translate("sensor", "Laser Control"))
        self.evenLaserButton.setText(_translate("sensor", "EVEN"))
        self.oddLaserButton.setText(_translate("sensor", "ODD"))
        self.hex4dCheckBox.setText(_translate("sensor", "Custom[Hex 4d]"))
        self.CurrentLaserPattern_label.setText(_translate("sensor", "Current Laser Pattern(No.1-16):"))
        self.cameraStatusLabel.setText(_translate("sensor", "!!No cameras were detected."))
        self.reconnectButton.setText(_translate("sensor", "Reconnect"))
        self.IPlabel.setText(_translate("sensor", "RPi adress"))
