# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sensorwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sensor(object):
    def setupUi(self, sensor):
        sensor.setObjectName("sensor")
        sensor.resize(909, 616)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(sensor)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.sensorImage = ImageViewer(sensor)
        self.sensorImage.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.sensorImage.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.sensorImage.setInteractive(False)
        self.sensorImage.setObjectName("sensorImage")
        self.verticalLayout_5.addWidget(self.sensorImage)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cameraStatusLabel = QtWidgets.QLabel(sensor)
        self.cameraStatusLabel.setObjectName("cameraStatusLabel")
        self.horizontalLayout_2.addWidget(self.cameraStatusLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridButton = QtWidgets.QPushButton(sensor)
        self.gridButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.gridButton.setCheckable(True)
        self.gridButton.setChecked(False)
        self.gridButton.setObjectName("gridButton")
        self.horizontalLayout_2.addWidget(self.gridButton)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.setStretch(0, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.scrollArea = QtWidgets.QScrollArea(sensor)
        self.scrollArea.setMaximumSize(QtCore.QSize(250, 16777215))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -234, 234, 830))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.layoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(0, -5, 242, 851))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.RPiAdressGroup = QtWidgets.QGroupBox(self.layoutWidget)
        self.RPiAdressGroup.setMinimumSize(QtCore.QSize(240, 110))
        self.RPiAdressGroup.setMaximumSize(QtCore.QSize(240, 16777215))
        self.RPiAdressGroup.setObjectName("RPiAdressGroup")
        self.layoutWidget1 = QtWidgets.QWidget(self.RPiAdressGroup)
        self.layoutWidget1.setGeometry(QtCore.QRect(13, 30, 211, 74))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.connectButton = QtWidgets.QPushButton(self.layoutWidget1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 201, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 117, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 215, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 201, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 117, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 215, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(186, 189, 182))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 201, 124))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 117, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 87, 31))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.connectButton.setPalette(palette)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout.addWidget(self.connectButton)
        self.disconnectButton = QtWidgets.QPushButton(self.layoutWidget1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(186, 189, 182))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.disconnectButton.setPalette(palette)
        self.disconnectButton.setObjectName("disconnectButton")
        self.horizontalLayout.addWidget(self.disconnectButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.IPlineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.IPlineEdit.setObjectName("IPlineEdit")
        self.horizontalLayout_4.addWidget(self.IPlineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.RPiAdressGroup)
        self.cameraControlGroup = QtWidgets.QGroupBox(self.layoutWidget)
        self.cameraControlGroup.setMinimumSize(QtCore.QSize(240, 280))
        self.cameraControlGroup.setMaximumSize(QtCore.QSize(240, 16777215))
        self.cameraControlGroup.setObjectName("cameraControlGroup")
        self.previewGroup = QtWidgets.QGroupBox(self.cameraControlGroup)
        self.previewGroup.setGeometry(QtCore.QRect(10, 119, 101, 71))
        self.previewGroup.setObjectName("previewGroup")
        self.prev1Button = QtWidgets.QPushButton(self.previewGroup)
        self.prev1Button.setGeometry(QtCore.QRect(10, 30, 31, 31))
        self.prev1Button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/GUI_icons/014-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prev1Button.setIcon(icon)
        self.prev1Button.setObjectName("prev1Button")
        self.prevAveButton = QtWidgets.QPushButton(self.previewGroup)
        self.prevAveButton.setGeometry(QtCore.QRect(60, 30, 31, 31))
        self.prevAveButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/GUI_icons/015-images.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prevAveButton.setIcon(icon1)
        self.prevAveButton.setObjectName("prevAveButton")
        self.consecutiveModeButton = QtWidgets.QPushButton(self.previewGroup)
        self.consecutiveModeButton.setGeometry(QtCore.QRect(60, 0, 20, 20))
        self.consecutiveModeButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/GUI_icons/133-spinner11.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.consecutiveModeButton.setIcon(icon2)
        self.consecutiveModeButton.setCheckable(True)
        self.consecutiveModeButton.setObjectName("consecutiveModeButton")
        self.preview_save_Group = QtWidgets.QGroupBox(self.cameraControlGroup)
        self.preview_save_Group.setGeometry(QtCore.QRect(120, 120, 101, 71))
        self.preview_save_Group.setObjectName("preview_save_Group")
        self.saveAveButton = QtWidgets.QPushButton(self.preview_save_Group)
        self.saveAveButton.setGeometry(QtCore.QRect(60, 30, 31, 31))
        self.saveAveButton.setText("")
        self.saveAveButton.setIcon(icon1)
        self.saveAveButton.setObjectName("saveAveButton")
        self.save1Button = QtWidgets.QPushButton(self.preview_save_Group)
        self.save1Button.setGeometry(QtCore.QRect(10, 30, 31, 31))
        self.save1Button.setText("")
        self.save1Button.setIcon(icon)
        self.save1Button.setObjectName("save1Button")
        self.layoutWidget2 = QtWidgets.QWidget(self.cameraControlGroup)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 211, 91))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget2)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.shutterLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.shutterLabel.setObjectName("shutterLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.shutterLabel)
        self.shutterLineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.shutterLineEdit.setText("")
        self.shutterLineEdit.setObjectName("shutterLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.shutterLineEdit)
        self.framesLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.framesLabel.setObjectName("framesLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.framesLabel)
        self.framesLineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.framesLineEdit.setText("")
        self.framesLineEdit.setObjectName("framesLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.framesLineEdit)
        self.ISOlabel = QtWidgets.QLabel(self.layoutWidget2)
        self.ISOlabel.setObjectName("ISOlabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.ISOlabel)
        self.ISOcombo = QtWidgets.QComboBox(self.layoutWidget2)
        self.ISOcombo.setEditable(True)
        self.ISOcombo.setObjectName("ISOcombo")
        self.ISOcombo.addItem("")
        self.ISOcombo.addItem("")
        self.ISOcombo.addItem("")
        self.ISOcombo.addItem("")
        self.ISOcombo.addItem("")
        self.ISOcombo.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ISOcombo)
        self.selectDirectoryButton = QtWidgets.QToolButton(self.cameraControlGroup)
        self.selectDirectoryButton.setGeometry(QtCore.QRect(190, 200, 26, 21))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/GUI_icons/049-folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.selectDirectoryButton.setIcon(icon3)
        self.selectDirectoryButton.setObjectName("selectDirectoryButton")
        self.saveDirecoryName = QtWidgets.QLabel(self.cameraControlGroup)
        self.saveDirecoryName.setGeometry(QtCore.QRect(10, 200, 171, 20))
        self.saveDirecoryName.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.saveDirecoryName.setText("")
        self.saveDirecoryName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.saveDirecoryName.setObjectName("saveDirecoryName")
        self.saveImgName = QtWidgets.QLabel(self.cameraControlGroup)
        self.saveImgName.setGeometry(QtCore.QRect(10, 226, 171, 20))
        self.saveImgName.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.saveImgName.setText("")
        self.saveImgName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.saveImgName.setObjectName("saveImgName")
        self.resetButton = QtWidgets.QPushButton(self.cameraControlGroup)
        self.resetButton.setGeometry(QtCore.QRect(190, 225, 41, 20))
        self.resetButton.setObjectName("resetButton")
        self.frameButton = QtWidgets.QPushButton(self.cameraControlGroup)
        self.frameButton.setGeometry(QtCore.QRect(185, 250, 50, 25))
        self.frameButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frameButton.setObjectName("frameButton")
        self.verticalLayout_3.addWidget(self.cameraControlGroup)
        self.laserControlGroup = QtWidgets.QGroupBox(self.layoutWidget)
        self.laserControlGroup.setMinimumSize(QtCore.QSize(240, 180))
        self.laserControlGroup.setMaximumSize(QtCore.QSize(240, 16777215))
        self.laserControlGroup.setObjectName("laserControlGroup")
        self.evenLaserButton = QtWidgets.QPushButton(self.laserControlGroup)
        self.evenLaserButton.setGeometry(QtCore.QRect(10, 30, 61, 25))
        self.evenLaserButton.setCheckable(True)
        self.evenLaserButton.setAutoExclusive(True)
        self.evenLaserButton.setObjectName("evenLaserButton")
        self.oddLaserButton = QtWidgets.QPushButton(self.laserControlGroup)
        self.oddLaserButton.setGeometry(QtCore.QRect(70, 30, 61, 25))
        self.oddLaserButton.setCheckable(True)
        self.oddLaserButton.setAutoExclusive(True)
        self.oddLaserButton.setObjectName("oddLaserButton")
        self.onAllLaserButton = QtWidgets.QPushButton(self.laserControlGroup)
        self.onAllLaserButton.setGeometry(QtCore.QRect(130, 30, 41, 25))
        self.onAllLaserButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/GUI_icons/lightON.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.onAllLaserButton.setIcon(icon4)
        self.onAllLaserButton.setCheckable(True)
        self.onAllLaserButton.setAutoExclusive(True)
        self.onAllLaserButton.setObjectName("onAllLaserButton")
        self.offAllLaserButton = QtWidgets.QPushButton(self.laserControlGroup)
        self.offAllLaserButton.setGeometry(QtCore.QRect(170, 30, 41, 25))
        self.offAllLaserButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/GUI_icons/lightOFF.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.offAllLaserButton.setIcon(icon5)
        self.offAllLaserButton.setCheckable(True)
        self.offAllLaserButton.setAutoExclusive(True)
        self.offAllLaserButton.setObjectName("offAllLaserButton")
        self.hex4dLineEdit = QtWidgets.QLineEdit(self.laserControlGroup)
        self.hex4dLineEdit.setEnabled(False)
        self.hex4dLineEdit.setGeometry(QtCore.QRect(60, 100, 91, 25))
        self.hex4dLineEdit.setObjectName("hex4dLineEdit")
        self.hex4dCheckBox = QtWidgets.QCheckBox(self.laserControlGroup)
        self.hex4dCheckBox.setEnabled(True)
        self.hex4dCheckBox.setGeometry(QtCore.QRect(20, 70, 131, 23))
        self.hex4dCheckBox.setAutoExclusive(True)
        self.hex4dCheckBox.setObjectName("hex4dCheckBox")
        self.setHex4dLaserButton = QtWidgets.QPushButton(self.laserControlGroup)
        self.setHex4dLaserButton.setEnabled(False)
        self.setHex4dLaserButton.setGeometry(QtCore.QRect(160, 100, 31, 25))
        self.setHex4dLaserButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/GUI_icons/exec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setHex4dLaserButton.setIcon(icon6)
        self.setHex4dLaserButton.setObjectName("setHex4dLaserButton")
        self.CurrentLaserPattern_label = QtWidgets.QLabel(self.laserControlGroup)
        self.CurrentLaserPattern_label.setGeometry(QtCore.QRect(10, 130, 221, 17))
        self.CurrentLaserPattern_label.setObjectName("CurrentLaserPattern_label")
        self.CurrentLaserPattern_value = QtWidgets.QLabel(self.laserControlGroup)
        self.CurrentLaserPattern_value.setGeometry(QtCore.QRect(10, 150, 211, 20))
        self.CurrentLaserPattern_value.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CurrentLaserPattern_value.setText("")
        self.CurrentLaserPattern_value.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentLaserPattern_value.setObjectName("CurrentLaserPattern_value")
        self.verticalLayout_3.addWidget(self.laserControlGroup)
        self.gridGroup = QtWidgets.QGroupBox(self.layoutWidget)
        self.gridGroup.setMinimumSize(QtCore.QSize(240, 235))
        self.gridGroup.setCheckable(True)
        self.gridGroup.setObjectName("gridGroup")
        self.layoutWidget_2 = QtWidgets.QWidget(self.gridGroup)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 30, 211, 201))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.typeLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.typeLabel.setObjectName("typeLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.typeLabel)
        self.gridTypeCombo = QtWidgets.QComboBox(self.layoutWidget_2)
        self.gridTypeCombo.setEditable(True)
        self.gridTypeCombo.setObjectName("gridTypeCombo")
        self.gridTypeCombo.addItem("")
        self.gridTypeCombo.addItem("")
        self.gridTypeCombo.addItem("")
        self.gridTypeCombo.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gridTypeCombo)
        self.linesLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.linesLabel.setObjectName("linesLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.linesLabel)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.xlabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.xlabel.setObjectName("xlabel")
        self.horizontalLayout_9.addWidget(self.xlabel)
        self.xLineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.xLineEdit.setObjectName("xLineEdit")
        self.horizontalLayout_9.addWidget(self.xLineEdit)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ylabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.ylabel.setObjectName("ylabel")
        self.horizontalLayout_6.addWidget(self.ylabel)
        self.yLineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.yLineEdit.setObjectName("yLineEdit")
        self.horizontalLayout_6.addWidget(self.yLineEdit)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.rotLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.rotLabel.setObjectName("rotLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.rotLabel)
        self.rotLineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.rotLineEdit.setObjectName("rotLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.rotLineEdit)
        self.gridColorLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.gridColorLabel.setObjectName("gridColorLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.gridColorLabel)
        self.gridColorCombo = QtWidgets.QComboBox(self.layoutWidget_2)
        self.gridColorCombo.setEditable(True)
        self.gridColorCombo.setObjectName("gridColorCombo")
        self.gridColorCombo.addItem("")
        self.gridColorCombo.addItem("")
        self.gridColorCombo.addItem("")
        self.gridColorCombo.addItem("")
        self.gridColorCombo.addItem("")
        self.gridColorCombo.addItem("")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.gridColorCombo)
        self.offsetLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.offsetLabel.setObjectName("offsetLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.offsetLabel)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.xlabel_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.xlabel_2.setObjectName("xlabel_2")
        self.horizontalLayout_11.addWidget(self.xlabel_2)
        self.xOffsetLineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.xOffsetLineEdit.setObjectName("xOffsetLineEdit")
        self.horizontalLayout_11.addWidget(self.xOffsetLineEdit)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.ylabel_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.ylabel_2.setObjectName("ylabel_2")
        self.horizontalLayout_12.addWidget(self.ylabel_2)
        self.yOffsetLineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.yOffsetLineEdit.setObjectName("yOffsetLineEdit")
        self.horizontalLayout_12.addWidget(self.yOffsetLineEdit)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_12)
        self.formLayout_2.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.alpha = QtWidgets.QLabel(self.layoutWidget_2)
        self.alpha.setObjectName("alpha")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.alpha)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.alphaLineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.alphaLineEdit.setText("")
        self.alphaLineEdit.setObjectName("alphaLineEdit")
        self.horizontalLayout_14.addWidget(self.alphaLineEdit)
        self.percentLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.percentLabel.setObjectName("percentLabel")
        self.horizontalLayout_14.addWidget(self.percentLabel)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_14)
        self.formLayout_2.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_13)
        self.verticalLayout_3.addWidget(self.gridGroup)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3.setStretch(4, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.scrollArea)

        self.retranslateUi(sensor)
        QtCore.QMetaObject.connectSlotsByName(sensor)

    def retranslateUi(self, sensor):
        _translate = QtCore.QCoreApplication.translate
        sensor.setWindowTitle(_translate("sensor", "Sensor Window"))
        self.cameraStatusLabel.setText(_translate("sensor", "CAMERA STATE"))
        self.gridButton.setText(_translate("sensor", "Grid"))
        self.RPiAdressGroup.setTitle(_translate("sensor", "RPi Adress"))
        self.connectButton.setText(_translate("sensor", "Connect"))
        self.disconnectButton.setText(_translate("sensor", "Disconnect"))
        self.cameraControlGroup.setTitle(_translate("sensor", "Camera Control"))
        self.previewGroup.setTitle(_translate("sensor", "Preview"))
        self.preview_save_Group.setTitle(_translate("sensor", "Preview\'n\'Save"))
        self.shutterLabel.setText(_translate("sensor", "Shutter [us]"))
        self.framesLabel.setText(_translate("sensor", "#~frames"))
        self.ISOlabel.setText(_translate("sensor", "ISO"))
        self.ISOcombo.setItemText(0, _translate("sensor", "100"))
        self.ISOcombo.setItemText(1, _translate("sensor", "200"))
        self.ISOcombo.setItemText(2, _translate("sensor", "400"))
        self.ISOcombo.setItemText(3, _translate("sensor", "800"))
        self.ISOcombo.setItemText(4, _translate("sensor", "1600"))
        self.ISOcombo.setItemText(5, _translate("sensor", "3200"))
        self.selectDirectoryButton.setText(_translate("sensor", "..."))
        self.resetButton.setText(_translate("sensor", "Reset"))
        self.frameButton.setText(_translate("sensor", "frame"))
        self.laserControlGroup.setTitle(_translate("sensor", "Laser Control"))
        self.evenLaserButton.setText(_translate("sensor", "EVEN"))
        self.oddLaserButton.setText(_translate("sensor", "ODD"))
        self.hex4dCheckBox.setText(_translate("sensor", "Custom[Hex 4d]"))
        self.CurrentLaserPattern_label.setText(_translate("sensor", "Current Laser Pattern(No.1-16):"))
        self.gridGroup.setTitle(_translate("sensor", "Grid"))
        self.typeLabel.setText(_translate("sensor", "Type"))
        self.gridTypeCombo.setItemText(0, _translate("sensor", "Solid"))
        self.gridTypeCombo.setItemText(1, _translate("sensor", "Dot"))
        self.gridTypeCombo.setItemText(2, _translate("sensor", "Dash"))
        self.gridTypeCombo.setItemText(3, _translate("sensor", "DashDot"))
        self.linesLabel.setText(_translate("sensor", "Lines"))
        self.xlabel.setText(_translate("sensor", "x:"))
        self.xLineEdit.setText(_translate("sensor", "3"))
        self.ylabel.setText(_translate("sensor", "y:"))
        self.yLineEdit.setText(_translate("sensor", "3"))
        self.rotLabel.setText(_translate("sensor", "Rot"))
        self.rotLineEdit.setText(_translate("sensor", "0.0"))
        self.gridColorLabel.setText(_translate("sensor", "Color"))
        self.gridColorCombo.setItemText(0, _translate("sensor", "Bright"))
        self.gridColorCombo.setItemText(1, _translate("sensor", "Dark"))
        self.gridColorCombo.setItemText(2, _translate("sensor", "Red"))
        self.gridColorCombo.setItemText(3, _translate("sensor", "Blue"))
        self.gridColorCombo.setItemText(4, _translate("sensor", "Green"))
        self.gridColorCombo.setItemText(5, _translate("sensor", "Yellow"))
        self.offsetLabel.setText(_translate("sensor", "Offset"))
        self.xlabel_2.setText(_translate("sensor", "x:"))
        self.xOffsetLineEdit.setText(_translate("sensor", "0.0"))
        self.ylabel_2.setText(_translate("sensor", "y:"))
        self.yOffsetLineEdit.setText(_translate("sensor", "0.0"))
        self.alpha.setText(_translate("sensor", "alpha"))
        self.percentLabel.setText(_translate("sensor", "%"))
from ImageViewScene import ImageViewer
import resources_rc
