# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ドキュメント\【MagikEye】\work\【projects】\keiganGUI\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_keigan(object):
    def setupUi(self, keigan):
        keigan.setObjectName("keigan")
        keigan.resize(775, 548)
        self.centralwidget = QtWidgets.QWidget(keigan)
        self.centralwidget.setObjectName("centralwidget")
        self.Settings = QtWidgets.QGroupBox(self.centralwidget)
        self.Settings.setEnabled(True)
        self.Settings.setGeometry(QtCore.QRect(60, 230, 311, 231))
        self.Settings.setAutoFillBackground(False)
        self.Settings.setFlat(False)
        self.Settings.setCheckable(True)
        self.Settings.setChecked(True)
        self.Settings.setObjectName("Settings")
        self.layoutWidget_3 = QtWidgets.QWidget(self.Settings)
        self.layoutWidget_3.setGeometry(QtCore.QRect(40, 150, 228, 61))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.presetLayout = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.presetLayout.setContentsMargins(0, 0, 0, 0)
        self.presetLayout.setObjectName("presetLayout")
        self.presetMotorCombo = QtWidgets.QComboBox(self.layoutWidget_3)
        self.presetMotorCombo.setObjectName("presetMotorCombo")
        self.presetMotorCombo.addItem("")
        self.presetMotorCombo.addItem("")
        self.presetMotorCombo.addItem("")
        self.presetLayout.addWidget(self.presetMotorCombo, 1, 0, 1, 1)
        self.presetLabel = QtWidgets.QLabel(self.layoutWidget_3)
        self.presetLabel.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.presetLabel.setFont(font)
        self.presetLabel.setObjectName("presetLabel")
        self.presetLayout.addWidget(self.presetLabel, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.presetValue = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.presetValue.setMinimumSize(QtCore.QSize(80, 0))
        self.presetValue.setObjectName("presetValue")
        self.horizontalLayout_3.addWidget(self.presetValue)
        self.unitLabel = QtWidgets.QLabel(self.layoutWidget_3)
        self.unitLabel.setMinimumSize(QtCore.QSize(30, 0))
        self.unitLabel.setObjectName("unitLabel")
        self.horizontalLayout_3.addWidget(self.unitLabel)
        self.presetLayout.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.presetExe = QtWidgets.QPushButton(self.layoutWidget_3)
        self.presetExe.setMaximumSize(QtCore.QSize(90, 16777215))
        self.presetExe.setAutoDefault(True)
        self.presetExe.setObjectName("presetExe")
        self.presetLayout.addWidget(self.presetExe, 0, 1, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(self.Settings)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 50, 191, 94))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sliderSpeedLabel = QtWidgets.QLabel(self.layoutWidget)
        self.sliderSpeedLabel.setObjectName("sliderSpeedLabel")
        self.verticalLayout_2.addWidget(self.sliderSpeedLabel)
        self.panSpeedLabel = QtWidgets.QLabel(self.layoutWidget)
        self.panSpeedLabel.setObjectName("panSpeedLabel")
        self.verticalLayout_2.addWidget(self.panSpeedLabel)
        self.tiltSpeedLabel = QtWidgets.QLabel(self.layoutWidget)
        self.tiltSpeedLabel.setObjectName("tiltSpeedLabel")
        self.verticalLayout_2.addWidget(self.tiltSpeedLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sliderSpeedSpin = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.sliderSpeedSpin.setDecimals(1)
        self.sliderSpeedSpin.setProperty("value", 20.0)
        self.sliderSpeedSpin.setObjectName("sliderSpeedSpin")
        self.verticalLayout_3.addWidget(self.sliderSpeedSpin)
        self.panSpeedSpin = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.panSpeedSpin.setDecimals(1)
        self.panSpeedSpin.setProperty("value", 5.0)
        self.panSpeedSpin.setObjectName("panSpeedSpin")
        self.verticalLayout_3.addWidget(self.panSpeedSpin)
        self.tiltSpeedSpin = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.tiltSpeedSpin.setDecimals(1)
        self.tiltSpeedSpin.setProperty("value", 5.0)
        self.tiltSpeedSpin.setObjectName("tiltSpeedSpin")
        self.verticalLayout_3.addWidget(self.tiltSpeedSpin)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radpersec = QtWidgets.QLabel(self.layoutWidget)
        self.radpersec.setMinimumSize(QtCore.QSize(40, 0))
        self.radpersec.setObjectName("radpersec")
        self.verticalLayout_4.addWidget(self.radpersec)
        self.radpersec_2 = QtWidgets.QLabel(self.layoutWidget)
        self.radpersec_2.setMinimumSize(QtCore.QSize(40, 0))
        self.radpersec_2.setObjectName("radpersec_2")
        self.verticalLayout_4.addWidget(self.radpersec_2)
        self.radpersec_3 = QtWidgets.QLabel(self.layoutWidget)
        self.radpersec_3.setMinimumSize(QtCore.QSize(40, 0))
        self.radpersec_3.setObjectName("radpersec_3")
        self.verticalLayout_4.addWidget(self.radpersec_3)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.setSpeedLabel = QtWidgets.QLabel(self.Settings)
        self.setSpeedLabel.setGeometry(QtCore.QRect(40, 30, 100, 16))
        self.setSpeedLabel.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.setSpeedLabel.setFont(font)
        self.setSpeedLabel.setObjectName("setSpeedLabel")
        self.robotControl = QtWidgets.QGroupBox(self.centralwidget)
        self.robotControl.setEnabled(True)
        self.robotControl.setGeometry(QtCore.QRect(60, 20, 401, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.robotControl.sizePolicy().hasHeightForWidth())
        self.robotControl.setSizePolicy(sizePolicy)
        self.robotControl.setObjectName("robotControl")
        self.layoutWidget1 = QtWidgets.QWidget(self.robotControl)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 30, 361, 115))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.robotControlLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.robotControlLayout.setContentsMargins(0, 0, 0, 0)
        self.robotControlLayout.setObjectName("robotControlLayout")
        self.panLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.panLabel.setObjectName("panLabel")
        self.robotControlLayout.addWidget(self.panLabel, 1, 0, 1, 1)
        self.tiltMoveExe = QtWidgets.QPushButton(self.layoutWidget1)
        self.tiltMoveExe.setAutoDefault(True)
        self.tiltMoveExe.setObjectName("tiltMoveExe")
        self.robotControlLayout.addWidget(self.tiltMoveExe, 2, 2, 1, 1)
        self.tiltPosSpin = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.tiltPosSpin.setDecimals(2)
        self.tiltPosSpin.setMinimum(-180.0)
        self.tiltPosSpin.setMaximum(180.0)
        self.tiltPosSpin.setSingleStep(0.1)
        self.tiltPosSpin.setObjectName("tiltPosSpin")
        self.robotControlLayout.addWidget(self.tiltPosSpin, 2, 1, 1, 1)
        self.sliderLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.sliderLabel.setObjectName("sliderLabel")
        self.robotControlLayout.addWidget(self.sliderLabel, 0, 0, 1, 1)
        self.panMoveExe = QtWidgets.QPushButton(self.layoutWidget1)
        self.panMoveExe.setAutoDefault(True)
        self.panMoveExe.setObjectName("panMoveExe")
        self.robotControlLayout.addWidget(self.panMoveExe, 1, 2, 1, 1)
        self.sliderMoveExe = QtWidgets.QPushButton(self.layoutWidget1)
        self.sliderMoveExe.setAutoDefault(True)
        self.sliderMoveExe.setObjectName("sliderMoveExe")
        self.robotControlLayout.addWidget(self.sliderMoveExe, 0, 2, 1, 1)
        self.panPosSpin = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.panPosSpin.setDecimals(2)
        self.panPosSpin.setMinimum(-180.0)
        self.panPosSpin.setMaximum(180.0)
        self.panPosSpin.setSingleStep(0.1)
        self.panPosSpin.setObjectName("panPosSpin")
        self.robotControlLayout.addWidget(self.panPosSpin, 1, 1, 1, 1)
        self.tiltLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.tiltLabel.setObjectName("tiltLabel")
        self.robotControlLayout.addWidget(self.tiltLabel, 2, 0, 1, 1)
        self.sliderPosSpin = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.sliderPosSpin.setDecimals(1)
        self.sliderPosSpin.setMinimum(-1000.0)
        self.sliderPosSpin.setMaximum(2100.0)
        self.sliderPosSpin.setSingleStep(5.0)
        self.sliderPosSpin.setObjectName("sliderPosSpin")
        self.robotControlLayout.addWidget(self.sliderPosSpin, 0, 1, 1, 1)
        self.goHomeButton = QtWidgets.QPushButton(self.robotControl)
        self.goHomeButton.setGeometry(QtCore.QRect(360, 160, 31, 28))
        self.goHomeButton.setObjectName("goHomeButton")
        self.setAsHomeButton = QtWidgets.QPushButton(self.robotControl)
        self.setAsHomeButton.setGeometry(QtCore.QRect(310, 160, 31, 28))
        self.setAsHomeButton.setObjectName("setAsHomeButton")
        self.MagikEye = QtWidgets.QPushButton(self.centralwidget)
        self.MagikEye.setGeometry(QtCore.QRect(510, 40, 101, 25))
        self.MagikEye.setAutoDefault(True)
        self.MagikEye.setObjectName("MagikEye")
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(490, 70, 141, 135))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.initializeButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.initializeButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.initializeButton.setAutoDefault(True)
        self.initializeButton.setObjectName("initializeButton")
        self.verticalLayout.addWidget(self.initializeButton)
        self.sliderOriginButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.sliderOriginButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.sliderOriginButton.setAutoDefault(True)
        self.sliderOriginButton.setObjectName("sliderOriginButton")
        self.verticalLayout.addWidget(self.sliderOriginButton)
        self.freeButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.freeButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.freeButton.setAutoDefault(True)
        self.freeButton.setObjectName("freeButton")
        self.verticalLayout.addWidget(self.freeButton)
        self.rebootButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.rebootButton.setMinimumSize(QtCore.QSize(50, 0))
        self.rebootButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.rebootButton.setAutoDefault(True)
        self.rebootButton.setDefault(False)
        self.rebootButton.setFlat(False)
        self.rebootButton.setObjectName("rebootButton")
        self.verticalLayout.addWidget(self.rebootButton)
        self.initializeProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.initializeProgressBar.setEnabled(False)
        self.initializeProgressBar.setGeometry(QtCore.QRect(490, 220, 118, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.initializeProgressBar.setFont(font)
        self.initializeProgressBar.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.initializeProgressBar.setProperty("value", 0)
        self.initializeProgressBar.setObjectName("initializeProgressBar")
        self.initializeProgressLabel = QtWidgets.QLabel(self.centralwidget)
        self.initializeProgressLabel.setEnabled(False)
        self.initializeProgressLabel.setGeometry(QtCore.QRect(490, 200, 161, 17))
        self.initializeProgressLabel.setObjectName("initializeProgressLabel")
        self.Script_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.Script_groupBox.setGeometry(QtCore.QRect(400, 260, 331, 111))
        self.Script_groupBox.setObjectName("Script_groupBox")
        self.showScriptName_label = QtWidgets.QLabel(self.Script_groupBox)
        self.showScriptName_label.setGeometry(QtCore.QRect(10, 30, 121, 17))
        self.showScriptName_label.setObjectName("showScriptName_label")
        self.scriptName_label = QtWidgets.QLabel(self.Script_groupBox)
        self.scriptName_label.setGeometry(QtCore.QRect(10, 50, 241, 21))
        self.scriptName_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scriptName_label.setText("")
        self.scriptName_label.setObjectName("scriptName_label")
        self.selectScriptButton = QtWidgets.QPushButton(self.Script_groupBox)
        self.selectScriptButton.setGeometry(QtCore.QRect(260, 50, 61, 25))
        self.selectScriptButton.setObjectName("selectScriptButton")
        self.executeScriptButton = QtWidgets.QPushButton(self.Script_groupBox)
        self.executeScriptButton.setGeometry(QtCore.QRect(260, 80, 61, 25))
        self.executeScriptButton.setObjectName("executeScriptButton")
        keigan.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(keigan)
        self.statusbar.setObjectName("statusbar")
        keigan.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(keigan)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 775, 26))
        self.menubar.setObjectName("menubar")
        keigan.setMenuBar(self.menubar)

        self.retranslateUi(keigan)
        QtCore.QMetaObject.connectSlotsByName(keigan)
        keigan.setTabOrder(self.initializeButton, self.sliderOriginButton)
        keigan.setTabOrder(self.sliderOriginButton, self.MagikEye)
        keigan.setTabOrder(self.MagikEye, self.sliderPosSpin)
        keigan.setTabOrder(self.sliderPosSpin, self.panPosSpin)
        keigan.setTabOrder(self.panPosSpin, self.tiltPosSpin)
        keigan.setTabOrder(self.tiltPosSpin, self.sliderMoveExe)
        keigan.setTabOrder(self.sliderMoveExe, self.panMoveExe)
        keigan.setTabOrder(self.panMoveExe, self.tiltMoveExe)
        keigan.setTabOrder(self.tiltMoveExe, self.sliderSpeedSpin)
        keigan.setTabOrder(self.sliderSpeedSpin, self.panSpeedSpin)
        keigan.setTabOrder(self.panSpeedSpin, self.tiltSpeedSpin)
        keigan.setTabOrder(self.tiltSpeedSpin, self.presetMotorCombo)
        keigan.setTabOrder(self.presetMotorCombo, self.presetValue)
        keigan.setTabOrder(self.presetValue, self.presetExe)
        keigan.setTabOrder(self.presetExe, self.Settings)
        keigan.setTabOrder(self.Settings, self.freeButton)
        keigan.setTabOrder(self.freeButton, self.selectScriptButton)
        keigan.setTabOrder(self.selectScriptButton, self.executeScriptButton)

    def retranslateUi(self, keigan):
        _translate = QtCore.QCoreApplication.translate
        keigan.setWindowTitle(_translate("keigan", "keiganGUI"))
        self.Settings.setTitle(_translate("keigan", "Settings"))
        self.presetMotorCombo.setItemText(0, _translate("keigan", "slider"))
        self.presetMotorCombo.setItemText(1, _translate("keigan", "pan"))
        self.presetMotorCombo.setItemText(2, _translate("keigan", "tilt"))
        self.presetLabel.setText(_translate("keigan", "Preset"))
        self.unitLabel.setText(_translate("keigan", "mm"))
        self.presetExe.setText(_translate("keigan", "execute"))
        self.sliderSpeedLabel.setText(_translate("keigan", "Slider"))
        self.panSpeedLabel.setText(_translate("keigan", "Pan"))
        self.tiltSpeedLabel.setText(_translate("keigan", "Tilt"))
        self.radpersec.setText(_translate("keigan", "rad/s"))
        self.radpersec_2.setText(_translate("keigan", "rad/s"))
        self.radpersec_3.setText(_translate("keigan", "rad/s"))
        self.setSpeedLabel.setText(_translate("keigan", "Set speed"))
        self.robotControl.setTitle(_translate("keigan", "Robot Control"))
        self.panLabel.setText(_translate("keigan", "Pan [-90 to 90 deg]"))
        self.tiltMoveExe.setText(_translate("keigan", "execute"))
        self.sliderLabel.setText(_translate("keigan", "Slider [-1000 to 2100 mm]"))
        self.panMoveExe.setText(_translate("keigan", "execute"))
        self.sliderMoveExe.setText(_translate("keigan", "execute"))
        self.tiltLabel.setText(_translate("keigan", "Tilt [-90 to 90 deg]"))
        self.goHomeButton.setText(_translate("keigan", "go"))
        self.setAsHomeButton.setText(_translate("keigan", "set"))
        self.MagikEye.setText(_translate("keigan", "●MagikEye●"))
        self.initializeButton.setText(_translate("keigan", "Initialize"))
        self.sliderOriginButton.setText(_translate("keigan", "Set Slider Origin"))
        self.freeButton.setText(_translate("keigan", "FREE all motors"))
        self.rebootButton.setText(_translate("keigan", "REBOOT all motors"))
        self.initializeProgressLabel.setText(_translate("keigan", "Initializing motors..."))
        self.Script_groupBox.setTitle(_translate("keigan", "Script"))
        self.showScriptName_label.setText(_translate("keigan", "Script to execute:"))
        self.selectScriptButton.setText(_translate("keigan", "select"))
        self.executeScriptButton.setText(_translate("keigan", "execute"))
